<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>button_Update Cart</name>
   <tag></tag>
   <elementGuidId>63b61a7a-d69f-4286-9149-12e35e627e43</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>button.button.primary.update-cart-button</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>(//button[@type='button'])[23]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:role=button[name=&quot;Update Cart&quot;i]</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>558e662f-58a7-42e7-b20b-3e6e04646e5f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>cfbe9040-8c73-418a-9142-acd3d137c535</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>button primary update-cart-button</value>
      <webElementGuid>2d05bb95-d7f2-4938-9ef9-d0cd9324793d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>role</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>e87d33b3-a214-44b2-8b47-abada6aa87a1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Update Cart</value>
      <webElementGuid>bfb69f41-59c1-408a-827c-141c8e7dee24</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;gwt_comshop_slipcover_pdp&quot;)/div[1]/div[@class=&quot;gwt-comshop-main-page-panel&quot;]/div[@class=&quot;gwt-comshop-product-display-panel&quot;]/div[@class=&quot;com-shop-pdp slipcover-template&quot;]/div[@class=&quot;gwt-com-pdp-tabbed-panel&quot;]/div[@class=&quot;gwt-sc-bottom-of-right&quot;]/div[@class=&quot;gwt-bottom-quantity-ATC&quot;]/button[@class=&quot;button primary update-cart-button&quot;]</value>
      <webElementGuid>12af558d-5a15-43c3-8dbb-c1585bed0204</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>(//button[@type='button'])[23]</value>
      <webElementGuid>ec2c26f6-a462-49e7-93e8-292a48c6a2d9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='gwt_comshop_slipcover_pdp']/div/div/div[2]/div[2]/div/div[2]/div[2]/button</value>
      <webElementGuid>f0b34d1e-c68f-4001-8b48-1d94aa151e49</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Sale $2,362.75'])[2]/following::button[3]</value>
      <webElementGuid>b6ffc422-a853-4326-87e1-d31012cc5193</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Was $2,684.00'])[2]/following::button[3]</value>
      <webElementGuid>f99b7727-f4ac-4878-ae25-3da4a015665d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='♥ Add to Wishlist or Registry'])[1]/preceding::button[1]</value>
      <webElementGuid>4e8d0c84-421b-4500-956d-afc25e3e9fb8</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div[2]/button</value>
      <webElementGuid>4cad6566-e3cb-4df8-b86c-3e18c682178d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//button[@type = 'button' and (text() = 'Update Cart' or . = 'Update Cart')]</value>
      <webElementGuid>a431acfc-cc32-4952-82d0-81b30b7f058c</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
