<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>button_Sale 2,517.86_incrementId</name>
   <tag></tag>
   <elementGuidId>6f07a4f0-844e-441b-8ec1-a8f0da56aef2</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#incrementId</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//button[@id='incrementId']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:label=&quot;increment quantity&quot;i</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>2ede78bd-730a-4de3-8428-bf9e99e0ec5d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>23133205-3be3-45ab-bf5c-d0ad5b9dcd34</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>button primary gwt-quantity-textbox-increment</value>
      <webElementGuid>50818aac-7256-4059-bc51-d39bee1a5cec</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>role</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>f3c3feca-2c37-4fe2-8e7e-fc71b3665217</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>incrementId</value>
      <webElementGuid>aaf5ceed-e8a9-4d9f-bcec-9cc12481210d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-label</name>
      <type>Main</type>
      <value>increment quantity</value>
      <webElementGuid>4585a102-7cbf-41e6-84ec-b70c332c941b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;incrementId&quot;)</value>
      <webElementGuid>8fd118b1-1ca5-4539-9da9-389db665c0f3</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//button[@id='incrementId']</value>
      <webElementGuid>c6d6024e-ddf4-4b6a-bf12-061c84ab7555</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='gwt_comshop_slipcover_pdp']/div/div/div[2]/div[2]/div/div[2]/div[2]/div/button[2]</value>
      <webElementGuid>bffa5d28-f246-4afe-8d63-e26771568346</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div[2]/div/button[2]</value>
      <webElementGuid>e16ce4f9-9cac-4437-9393-471a0fff19c6</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//button[@type = 'button' and @id = 'incrementId']</value>
      <webElementGuid>ddc5969d-b579-4bd6-8579-b3e293e23157</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
