<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>iframe_Your offer_fcopt-offer-68948-content</name>
   <tag></tag>
   <elementGuidId>b668e7d8-9ac2-4d00-a726-988feedf3f90</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#fcopt-offer-68948-content</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//iframe[@id='fcopt-offer-68948-content']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>iframe[title=&quot;Welcome Dialog&quot;]</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>iframe</value>
      <webElementGuid>6c04f0fe-180f-472a-abd9-a662929e9c23</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>fcopt-offer-68948-content</value>
      <webElementGuid>eadc2f8b-80fe-48bc-ac45-f5dee3f91ed3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>frameborder</name>
      <type>Main</type>
      <value>0</value>
      <webElementGuid>78972f6c-218f-4a52-8d32-c7fcc25710d6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>width</name>
      <type>Main</type>
      <value>100%</value>
      <webElementGuid>b9b8f58a-d703-474b-aa4e-4783274db1b9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>height</name>
      <type>Main</type>
      <value>100%</value>
      <webElementGuid>17d44bee-244c-4b25-a7af-4f851362c91d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>scrolling</name>
      <type>Main</type>
      <value>no</value>
      <webElementGuid>b95eff15-d351-462d-9b79-14844762ad69</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>title</name>
      <type>Main</type>
      <value>Welcome Dialog</value>
      <webElementGuid>82cafe41-c19e-4434-b704-7824ea9d7e4f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>src</name>
      <type>Main</type>
      <value>https://api.securedvisit.com/lightbox/client/1150_03659/?fp=5d0bf20c977f102e13db9dc2b400e892&amp;m=form&amp;form_id=68948&amp;promo_id=8804&amp;v=1713027886701</value>
      <webElementGuid>adc4e2c9-6dab-4ae9-a0f7-dddcf4ac1971</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;fcopt-offer-68948-content&quot;)</value>
      <webElementGuid>3f641d96-62c8-4b47-93a8-97776b50c2aa</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//iframe[@id='fcopt-offer-68948-content']</value>
      <webElementGuid>4e7bd458-e723-49af-a2a0-7037c9ad1a1b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='fcopt-onsite-app-68948_wrapper']/div[2]/div/div/iframe</value>
      <webElementGuid>7cd751ad-d84d-4432-bb94-360be928a1ca</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div/div/iframe</value>
      <webElementGuid>1478a718-e152-429b-bf62-9f92cd600ebd</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//iframe[@id = 'fcopt-offer-68948-content' and @title = 'Welcome Dialog' and @src = 'https://api.securedvisit.com/lightbox/client/1150_03659/?fp=5d0bf20c977f102e13db9dc2b400e892&amp;m=form&amp;form_id=68948&amp;promo_id=8804&amp;v=1713027886701']</value>
      <webElementGuid>f3115cf5-01fd-4796-b735-f7291e2c9122</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
