<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>img_For fabric names and description hold m_191161_1</name>
   <tag></tag>
   <elementGuidId>93183157-6b0b-4bfc-afe7-d0454b9276ee</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>tr:nth-of-type(3) > td > table.gwt-comshop-fabric-image-panel > tbody > tr > td > div.gwt-PDP-Fabric-Image-panel > img.gwt-pdp-swatch-thumbnail-image</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='gwt-comshop-slipcover-customization-sub-tab-panel']/table/tbody/tr[2]/td/div/div/table/tbody/tr[3]/td/table/tbody/tr[3]/td/table/tbody/tr/td/div/img</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:role=img[name=&quot;Gowan White Insideout&quot;i]</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>img</value>
      <webElementGuid>391a5f02-6771-4b9c-b547-05d01ef49970</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>gwt-pdp-swatch-thumbnail-image</value>
      <webElementGuid>048d0db7-16a6-42c3-9473-07a40f905b1e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>alt</name>
      <type>Main</type>
      <value>Gowan White Insideout                                                                                                           </value>
      <webElementGuid>8127b9f8-5a34-4312-9473-1b5caf76c2b9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-siid</name>
      <type>Main</type>
      <value>16</value>
      <webElementGuid>485c6fa3-6b6a-48c4-bc82-0ea586f33a7d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tabindex</name>
      <type>Main</type>
      <value>0</value>
      <webElementGuid>3010db69-bb36-4470-abdb-bfbc913f2249</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>title</name>
      <type>Main</type>
      <value>Gowan White Insideout                                                                                                           </value>
      <webElementGuid>b67a152a-2da2-41d9-b8b3-7c6355dbc734</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>src</name>
      <type>Main</type>
      <value>https://akamai-scene7.ballarddesigns.com/is/image/ballarddesigns//GWWH?$wcom$</value>
      <webElementGuid>7aba95fb-636a-4387-b395-6c5250df8dc3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;gwt-comshop-slipcover-customization-sub-tab-panel&quot;)/table[@class=&quot;gwt-fabric-filtering-panel&quot;]/tbody[1]/tr[2]/td[1]/div[@class=&quot;gwt-comshop-fabric-swatch-scroll-panel&quot;]/div[1]/table[1]/tbody[1]/tr[3]/td[1]/table[@class=&quot;gwt-comshop-fabric-flex-table&quot;]/tbody[1]/tr[3]/td[1]/table[@class=&quot;gwt-comshop-fabric-image-panel&quot;]/tbody[1]/tr[1]/td[1]/div[@class=&quot;gwt-PDP-Fabric-Image-panel&quot;]/img[@class=&quot;gwt-pdp-swatch-thumbnail-image&quot;]</value>
      <webElementGuid>74283b69-8bd7-4634-942b-dd9d31433422</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='gwt-comshop-slipcover-customization-sub-tab-panel']/table/tbody/tr[2]/td/div/div/table/tbody/tr[3]/td/table/tbody/tr[3]/td/table/tbody/tr/td/div/img</value>
      <webElementGuid>bf8e7a8c-95df-4a7d-8050-6cc4a002ac03</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:img</name>
      <type>Main</type>
      <value>//img[@alt='Gowan White Insideout                                                                                                           ']</value>
      <webElementGuid>1f3e8235-3790-44a8-b265-3f93a5742d93</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//tr[3]/td/table/tbody/tr/td/div/img</value>
      <webElementGuid>5c12148a-130f-407d-9838-0099dd14986d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//img[@alt = 'Gowan White Insideout                                                                                                           ' and @title = 'Gowan White Insideout                                                                                                           ' and @src = 'https://akamai-scene7.ballarddesigns.com/is/image/ballarddesigns//GWWH?$wcom$']</value>
      <webElementGuid>5730ed72-1e06-4426-b7ce-181789feeed9</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
