<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>img_For fabric names and description hold m_191161</name>
   <tag></tag>
   <elementGuidId>d76b0565-f56b-4f63-aa62-3956aaa5c227</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>tr:nth-of-type(4) > td:nth-of-type(3) > table.gwt-comshop-fabric-image-panel > tbody > tr > td > div.gwt-PDP-Fabric-Image-panel > img.gwt-pdp-swatch-thumbnail-image</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='gwt-comshop-slipcover-customization-sub-tab-panel']/table/tbody/tr[2]/td/div/div/table/tbody/tr[3]/td/table/tbody/tr[4]/td[3]/table/tbody/tr/td/div/img</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:role=img[name=&quot;Tillie Gingham Black Insideout Performance&quot;i]</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>img</value>
      <webElementGuid>b34e1ea9-eaf4-4b59-9728-769e930ef327</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>gwt-pdp-swatch-thumbnail-image</value>
      <webElementGuid>a52427a4-8844-4f97-bd86-2fe750914d27</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>alt</name>
      <type>Main</type>
      <value>Tillie Gingham Black Insideout Performance                                                                                      </value>
      <webElementGuid>2e7c616e-f1e1-424b-9c36-dd9ea8fee691</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-siid</name>
      <type>Main</type>
      <value>19</value>
      <webElementGuid>de24660d-d269-44be-aab9-aee7dff92eac</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tabindex</name>
      <type>Main</type>
      <value>0</value>
      <webElementGuid>1bb60e26-3fba-48a9-a10c-1d22c93f5598</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>title</name>
      <type>Main</type>
      <value>Tillie Gingham Black Insideout Performance                                                                                      </value>
      <webElementGuid>9fddb3e9-5b36-4023-9b07-8c8eca94c2bb</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>src</name>
      <type>Main</type>
      <value>https://akamai-scene7.ballarddesigns.com/is/image/ballarddesigns//TGBK?$wcom$</value>
      <webElementGuid>01a98dd5-383e-40fa-8748-b6e42feb3d14</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;gwt-comshop-slipcover-customization-sub-tab-panel&quot;)/table[@class=&quot;gwt-fabric-filtering-panel&quot;]/tbody[1]/tr[2]/td[1]/div[@class=&quot;gwt-comshop-fabric-swatch-scroll-panel&quot;]/div[1]/table[1]/tbody[1]/tr[3]/td[1]/table[@class=&quot;gwt-comshop-fabric-flex-table&quot;]/tbody[1]/tr[4]/td[3]/table[@class=&quot;gwt-comshop-fabric-image-panel&quot;]/tbody[1]/tr[1]/td[1]/div[@class=&quot;gwt-PDP-Fabric-Image-panel&quot;]/img[@class=&quot;gwt-pdp-swatch-thumbnail-image&quot;]</value>
      <webElementGuid>48b805d6-62e0-45e8-95b3-705e370988c5</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='gwt-comshop-slipcover-customization-sub-tab-panel']/table/tbody/tr[2]/td/div/div/table/tbody/tr[3]/td/table/tbody/tr[4]/td[3]/table/tbody/tr/td/div/img</value>
      <webElementGuid>79743c40-8ad1-4d53-b9fd-6014d1abe7ed</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:img</name>
      <type>Main</type>
      <value>//img[@alt='Tillie Gingham Black Insideout Performance                                                                                      ']</value>
      <webElementGuid>1ae4adcb-bf25-4005-8ee2-537627203040</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//tr[4]/td[3]/table/tbody/tr/td/div/img</value>
      <webElementGuid>66b8b9ab-b940-42e7-acca-8211e98b4154</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//img[@alt = 'Tillie Gingham Black Insideout Performance                                                                                      ' and @title = 'Tillie Gingham Black Insideout Performance                                                                                      ' and @src = 'https://akamai-scene7.ballarddesigns.com/is/image/ballarddesigns//TGBK?$wcom$']</value>
      <webElementGuid>913bff94-ac04-4c2b-9510-0800b43fb032</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
