<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>span_X</name>
   <tag></tag>
   <elementGuidId>ea76f3c1-9af8-442e-b1ea-db04f1166d27</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#Close1-Item124 > button.offer-control.close > span</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='Close1-Item124']/button/span</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:label=&quot;Close Dialog&quot;s</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>span</value>
      <webElementGuid>70aa5979-7349-4677-bb18-a633ad1a97e4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>X</value>
      <webElementGuid>5d1faa2e-5201-4e01-a028-a557e9f60ef6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;Close1-Item124&quot;)/button[@class=&quot;offer-control close&quot;]/span[1]</value>
      <webElementGuid>55703de4-30ac-492c-84af-fe41a91f406d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ref_element</name>
      <type>Main</type>
      <value>Object Repository/Page_Baldwin Club Chair Slipcover - Special_bd9583/iframe_Your offer_fcopt-offer-68948-content</value>
      <webElementGuid>9b3ebfed-d309-4cae-96ce-34b3836ed5c8</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='Close1-Item124']/button/span</value>
      <webElementGuid>798cacd9-5abe-422d-9d4a-f5b63e3c8699</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='NO THANK YOU'])[1]/following::span[1]</value>
      <webElementGuid>c5305b95-d1c2-49a0-a6ef-d04a4f7c5188</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='By clicking submit, you agree to receive emails from Ballard Designs.'])[1]/following::span[2]</value>
      <webElementGuid>9e3c78af-50aa-45e1-b566-183e54998227</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='X']/parent::*</value>
      <webElementGuid>e898c4a0-b1ee-4a4d-a3b7-fe9542262b1c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[9]/button/span</value>
      <webElementGuid>31e15bfa-101e-4301-9254-a560e29b4cbf</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//span[(text() = 'X' or . = 'X')]</value>
      <webElementGuid>ab0695aa-5f95-4e60-862a-af96b7de48e4</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
