<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>button_In-stock usually ships in 1-7 busine_2d3f42</name>
   <tag></tag>
   <elementGuidId>9ee4d952-037e-43f0-93b0-422aae54f977</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#incrementId</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//button[@id='incrementId']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>#quantity_693635 >> internal:label=&quot;increment quantity&quot;i</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>9b43c040-dafa-4bfa-a7d4-a7a5b3402fbe</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>2ad03972-f3ec-49c8-b618-59b6f18dafa9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>button primary gwt-quantity-textbox-increment</value>
      <webElementGuid>0b8210fa-c9e1-4a31-9429-7b28f3a1b3cc</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>role</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>418f4b4a-c08a-471c-ab92-43fe5cc2548a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>incrementId</value>
      <webElementGuid>5b2c862a-f941-4774-af87-cb84753a70a7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-label</name>
      <type>Main</type>
      <value>increment quantity</value>
      <webElementGuid>238b2697-8f85-4a62-a952-28ce5f64c1f2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;quantity_693635&quot;)/button[@id=&quot;incrementId&quot;]</value>
      <webElementGuid>44ebaf8f-9df8-44a4-b59e-1a4f355a4693</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//button[@id='incrementId']</value>
      <webElementGuid>b443eea1-08ab-4309-b43c-96e1dc73758a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='quantity_693635']/button[2]</value>
      <webElementGuid>9dec50fc-8906-40d3-af08-127a5814f49f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div/div/button[2]</value>
      <webElementGuid>1dcc70b9-d953-40ee-8d24-bda9c804890b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//button[@type = 'button' and @id = 'incrementId']</value>
      <webElementGuid>79b8e378-7ade-4c72-9038-63739bad7407</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
