<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>button_Add To Cart</name>
   <tag></tag>
   <elementGuidId>97d79cca-6ab0-420b-ba52-b00937b92eed</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#gwt-add-to-cart-btn</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//button[@id='gwt-add-to-cart-btn']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>#gwt-product-detail-widget-id-693635 >> internal:role=button[name=&quot;Add To Cart&quot;i]</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>44d3c51a-1275-4485-96fe-26ea86f94f7b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>5dfa1f2f-d39b-4997-8688-971a0e8bfb87</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>button primary</value>
      <webElementGuid>a101566e-6292-48b5-b78b-ae6f203c5e92</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>role</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>d3150265-302f-4390-8bfb-889817a3ec7f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>gwt-add-to-cart-btn</value>
      <webElementGuid>5298ab02-4948-48a7-bd4e-9d73350b1d97</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>catentryid</name>
      <type>Main</type>
      <value>693635</value>
      <webElementGuid>8833c156-6069-4f1c-ae3b-d44563c7e168</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Add To Cart</value>
      <webElementGuid>7032c5e8-9c8f-41bc-a62f-c5b9d533c3d0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;gwt-product-detail-widget-id-693635&quot;)/div[@class=&quot;product-detail-widget-bottom-links-panel&quot;]/div[@class=&quot;gwt-product-detail-widget-price-column qty-selector-add-to-cart-panel&quot;]/div[@class=&quot;gwt-bundle-add-to-cart-btn&quot;]/button[@id=&quot;gwt-add-to-cart-btn&quot;]</value>
      <webElementGuid>fa00e518-6aaa-4393-8797-e3877e08160d</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//button[@id='gwt-add-to-cart-btn']</value>
      <webElementGuid>d534461f-7ff5-48be-9407-78612aa0fb9b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='gwt-product-detail-widget-id-693635']/div[4]/div[2]/div[2]/button</value>
      <webElementGuid>1a62e4cf-d2c0-441c-accd-cdfd77da06d7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='In-stock usually ships in 1-7 business days.'])[1]/following::button[3]</value>
      <webElementGuid>7cafa9d5-5eac-4aee-8e5f-785ee42c6d3f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='$49.00'])[1]/following::button[3]</value>
      <webElementGuid>e992ea7f-6a45-4f2a-93d3-fc241beeead9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='♥ Add to Wishlist or Registry'])[1]/preceding::button[1]</value>
      <webElementGuid>3f4b7bef-957e-4d88-80ba-23ca374a9e1a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[4]/div[2]/div[2]/button</value>
      <webElementGuid>59b57016-07b7-4625-be4b-fe00a6f3faf8</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//button[@type = 'button' and @id = 'gwt-add-to-cart-btn' and (text() = 'Add To Cart' or . = 'Add To Cart')]</value>
      <webElementGuid>8f01eafd-bc9b-42f2-9ab9-8105a324a40a</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
