<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>iframe_Your offer_fcopt-offer-68948-content</name>
   <tag></tag>
   <elementGuidId>60fa43d9-084d-49c0-9f3d-0ad9c3d8bfc8</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#fcopt-offer-68948-content</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//iframe[@id='fcopt-offer-68948-content']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>iframe[title=&quot;Welcome Dialog&quot;]</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>iframe</value>
      <webElementGuid>76c5de77-4d1b-4edf-a741-3077974c43c8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>fcopt-offer-68948-content</value>
      <webElementGuid>acc23d23-2769-486f-a06f-867d3ced1066</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>frameborder</name>
      <type>Main</type>
      <value>0</value>
      <webElementGuid>cdb3e1e1-52dc-481a-844f-4dcd5feb26e9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>width</name>
      <type>Main</type>
      <value>100%</value>
      <webElementGuid>1cbb6c8a-1279-4541-b4b9-3d5362343b85</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>height</name>
      <type>Main</type>
      <value>100%</value>
      <webElementGuid>982a19a4-3918-46b4-9bce-062512b93753</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>scrolling</name>
      <type>Main</type>
      <value>no</value>
      <webElementGuid>2cf6062f-0835-4cbb-81af-a47c734f08b2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>title</name>
      <type>Main</type>
      <value>Welcome Dialog</value>
      <webElementGuid>408c07ad-f367-4c9f-a8c1-9f9e458117c5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>src</name>
      <type>Main</type>
      <value>https://api.securedvisit.com/lightbox/client/1150_03659/?fp=e1eabae0c1b1b8ae8440b18e99a4628e&amp;m=form&amp;form_id=68948&amp;promo_id=8804&amp;v=1712572792696</value>
      <webElementGuid>a41536b7-d45d-4575-990a-64f111862aa9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;fcopt-offer-68948-content&quot;)</value>
      <webElementGuid>f2404b3b-406f-4f2d-b9f9-51afbcb292f9</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//iframe[@id='fcopt-offer-68948-content']</value>
      <webElementGuid>0ceb2215-b34c-45c2-92a0-a7c6b1ccff20</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='fcopt-onsite-app-68948_wrapper']/div[2]/div/div/iframe</value>
      <webElementGuid>44a70abe-c1b6-42fe-8143-8c4dae212e19</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div/div/iframe</value>
      <webElementGuid>1aab3e21-2bfc-4351-9061-ad3707d539dc</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//iframe[@id = 'fcopt-offer-68948-content' and @title = 'Welcome Dialog' and @src = 'https://api.securedvisit.com/lightbox/client/1150_03659/?fp=e1eabae0c1b1b8ae8440b18e99a4628e&amp;m=form&amp;form_id=68948&amp;promo_id=8804&amp;v=1712572792696']</value>
      <webElementGuid>a324cbef-1079-4724-895f-ecdd80d347a3</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
