<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>a_Edit</name>
   <tag></tag>
   <elementGuidId>dbb9776c-eec1-4eb8-af8a-b5cd9e7193c3</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>a.order-item-link.edit-link.action</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='shopping-cart-v2-root']/div/div[2]/div/div[4]/div/div[2]/div/div[2]/div[11]/a</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:role=link[name=&quot;Edit&quot;i]</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>a2217c96-8183-479d-8c91-ab763e8b5b68</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>order-item-link edit-link action</value>
      <webElementGuid>674ab827-6351-4745-b6ec-d54327bb5cfe</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>javascript:;</value>
      <webElementGuid>f3851e74-4b6f-457d-af0d-58fb70731ddb</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Edit</value>
      <webElementGuid>4eb6d9ca-9397-4916-b4a7-a98531587bf4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;shopping-cart-v2-root&quot;)/div[@class=&quot;shopping-cart-v2&quot;]/div[@class=&quot;main-panel&quot;]/div[@class=&quot;left-main-panel&quot;]/div[@class=&quot;items-container&quot;]/div[@class=&quot;order-item-display-widget-v2 order-item-with-personalization&quot;]/div[@class=&quot;order-item-display-wrapper&quot;]/div[@class=&quot;order-item-info-panel&quot;]/div[@class=&quot;order-item-details-panel&quot;]/div[@class=&quot;order-item-bottom-links-panel&quot;]/a[@class=&quot;order-item-link edit-link action&quot;]</value>
      <webElementGuid>16be2f6b-4db5-4549-9fcc-91c2d8047e3d</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='shopping-cart-v2-root']/div/div[2]/div/div[4]/div/div[2]/div/div[2]/div[11]/a</value>
      <webElementGuid>77734c7d-9a84-4abd-aa40-a83f9118c548</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:link</name>
      <type>Main</type>
      <value>//a[contains(text(),'Edit')]</value>
      <webElementGuid>8a6addad-0696-486f-b19e-9ffc6d5877fd</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Spa'])[1]/following::a[1]</value>
      <webElementGuid>d71754ef-5eea-4a7b-83d0-f1d762a2c161</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)=':'])[4]/following::a[1]</value>
      <webElementGuid>2643a8a3-a993-4f40-b180-6a8b806cc13c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Remove'])[1]/preceding::a[1]</value>
      <webElementGuid>af6bd094-3278-4053-8172-d9dba0de3b19</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Save for Later'])[1]/preceding::a[2]</value>
      <webElementGuid>cd9a9e3a-0aa2-47a6-9428-c85954d0fe72</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Edit']/parent::*</value>
      <webElementGuid>074af192-1b27-4905-b00f-d043fd9b6116</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>(//a[contains(@href, 'javascript:;')])[2]</value>
      <webElementGuid>532753ed-5465-446d-92fe-633561559258</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[11]/a</value>
      <webElementGuid>1f9760c3-045f-438d-a091-c8bf6f741513</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@href = 'javascript:;' and (text() = 'Edit' or . = 'Edit')]</value>
      <webElementGuid>f5a62ca6-24d4-4b7b-a9c1-927653f809ca</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
