<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>a_Remove</name>
   <tag></tag>
   <elementGuidId>2ad08971-b7a0-447f-9e1d-7750cc8b7cd5</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>a.order-item-link.remove-link.action</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='shopping-cart-v2-root']/div/div[2]/div/div[4]/div/div/div/div[2]/div[11]/a[2]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:role=link[name=&quot;Remove&quot;i]</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>e466897a-fe8b-4919-a067-9b959b554270</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>order-item-link remove-link action</value>
      <webElementGuid>8f899d5e-a089-4a87-b49e-177dbe34f2ad</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>javascript:;</value>
      <webElementGuid>e715c630-6834-4cc0-bb22-515653b8c602</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Remove</value>
      <webElementGuid>a1ded052-cf95-49af-8fa3-9125ec26c838</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;shopping-cart-v2-root&quot;)/div[@class=&quot;shopping-cart-v2&quot;]/div[@class=&quot;main-panel&quot;]/div[@class=&quot;left-main-panel&quot;]/div[@class=&quot;items-container&quot;]/div[@class=&quot;order-item-display-widget-v2 order-item-with-personalization&quot;]/div[@class=&quot;order-item-display-wrapper&quot;]/div[@class=&quot;order-item-info-panel&quot;]/div[@class=&quot;order-item-details-panel&quot;]/div[@class=&quot;order-item-bottom-links-panel&quot;]/a[@class=&quot;order-item-link remove-link action&quot;]</value>
      <webElementGuid>d1cde2ab-1d3a-4348-9aa7-51c16b7d46d8</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='shopping-cart-v2-root']/div/div[2]/div/div[4]/div/div/div/div[2]/div[11]/a[2]</value>
      <webElementGuid>7b1c0ef1-669b-4151-bf26-89ae18eed9df</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:link</name>
      <type>Main</type>
      <value>//a[contains(text(),'Remove')]</value>
      <webElementGuid>afc2d401-4c82-4e87-944f-1efb5afbcccd</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Edit'])[1]/following::a[1]</value>
      <webElementGuid>3c03d174-3ad1-4244-96f3-0bd5ab141375</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Teal'])[1]/following::a[2]</value>
      <webElementGuid>e9a10557-ae2b-44c1-9782-6fa5815a085e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Save for Later'])[1]/preceding::a[1]</value>
      <webElementGuid>a04874a9-92ed-4e46-b965-11f0b6ca624b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Was $59.00'])[1]/preceding::a[2]</value>
      <webElementGuid>4b5b1cce-5ccc-4efd-938e-96304ce43b55</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Remove']/parent::*</value>
      <webElementGuid>f62b643a-dfbd-4202-87a8-af75193f9c66</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>(//a[contains(@href, 'javascript:;')])[3]</value>
      <webElementGuid>37617b3e-d3c9-4899-b4da-1002d4dbdb1a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[11]/a[2]</value>
      <webElementGuid>a4b6d9a1-558b-4626-8b61-96af35b31e18</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@href = 'javascript:;' and (text() = 'Remove' or . = 'Remove')]</value>
      <webElementGuid>c3ffd698-095f-430c-8f8a-60cd923930b1</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
