<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>button_49.00_decrementId</name>
   <tag></tag>
   <elementGuidId>5e0fddee-6e01-41db-a41d-96141faa4bfd</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#decrementId</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//button[@id='decrementId']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:label=&quot;decrement quantity&quot;i</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>b75ef409-5a0f-4d35-b60e-439e28721650</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>37d9fb3a-84d1-43b3-8aa8-9984622523fb</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>button primary gwt-quantity-textbox-decrement</value>
      <webElementGuid>704bffa8-3e5f-44ab-8f7b-b96852b40286</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>role</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>30efc85f-a89b-437d-8f93-6ec2b865d13f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>decrementId</value>
      <webElementGuid>fb9785f1-9ecd-46bc-858d-0d35d598f0d0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-label</name>
      <type>Main</type>
      <value>decrement quantity</value>
      <webElementGuid>896229fc-4db6-4281-b811-ef30fe999b68</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;decrementId&quot;)</value>
      <webElementGuid>1eaf5893-b842-41af-b8fd-7a42f0763414</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//button[@id='decrementId']</value>
      <webElementGuid>b66a7f8d-79db-4abd-a6c2-438b56c10db1</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='shopping-cart-v2-root']/div/div[2]/div/div[4]/div/div/div[3]/div/div/button</value>
      <webElementGuid>1b2aa37b-f68c-462d-af57-9ca896fa9ea2</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[3]/div/div/button</value>
      <webElementGuid>3cac2eb3-fda4-4bec-aba2-c052650e1c7e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//button[@type = 'button' and @id = 'decrementId']</value>
      <webElementGuid>b6cdf4dc-37bb-4251-88a0-6e4f63f30d83</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
