<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>div_Carriage House 6-Light Pendant - Extra Large</name>
   <tag></tag>
   <elementGuidId>961c3273-d953-48bc-ad7a-60abcc3eff07</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>div.gwt-oid-name</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='shopping-cart-v2-root']/div/div[2]/div/div[4]/div/div[2]/div/div[2]/div/div</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:role=button[name=&quot;Carriage House 6-Light Pendant - Extra Large&quot;i]</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>5295750f-3660-4938-a6f6-822283caa6e0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>gwt-oid-name</value>
      <webElementGuid>d2ef7aa0-4262-4dc2-84f3-bb6156f158ea</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>role</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>56e5392e-b72d-48d6-8535-ecc88066fd03</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tabindex</name>
      <type>Main</type>
      <value>0</value>
      <webElementGuid>fbe267c3-6fea-4a30-912e-fcece8b4d07a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Carriage House 6-Light Pendant - Extra Large</value>
      <webElementGuid>062dc0d5-ccf9-4bcc-b7f6-f077889d2a2b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;shopping-cart-v2-root&quot;)/div[@class=&quot;shopping-cart-v2&quot;]/div[@class=&quot;main-panel&quot;]/div[@class=&quot;left-main-panel&quot;]/div[@class=&quot;items-container&quot;]/div[@class=&quot;order-item-display-widget-v2&quot;]/div[@class=&quot;order-item-display-wrapper&quot;]/div[@class=&quot;order-item-info-panel&quot;]/div[@class=&quot;order-item-details-panel&quot;]/div[@class=&quot;order-item-name&quot;]/div[@class=&quot;gwt-oid-name&quot;]</value>
      <webElementGuid>5f6b19c8-a390-4660-a89e-e212156e445f</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='shopping-cart-v2-root']/div/div[2]/div/div[4]/div/div[2]/div/div[2]/div/div</value>
      <webElementGuid>53fc558a-eeb6-45f8-b209-9a55ea9eee77</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='shoppers'])[1]/following::div[9]</value>
      <webElementGuid>c2f7b7fe-64cf-41b3-b594-85d565088377</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Finish'])[1]/preceding::div[2]</value>
      <webElementGuid>2cebb801-475a-46ed-804c-51b454e32f68</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)=':'])[1]/preceding::div[2]</value>
      <webElementGuid>6c0071da-7507-449b-80e4-677d53d186b0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Carriage House 6-Light Pendant - Extra Large']/parent::*</value>
      <webElementGuid>93b65574-bea6-4916-82bf-86247b549b58</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[4]/div/div[2]/div/div[2]/div/div</value>
      <webElementGuid>c6986597-fefc-434b-b6c4-aec9acc673d5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//div[(text() = 'Carriage House 6-Light Pendant - Extra Large' or . = 'Carriage House 6-Light Pendant - Extra Large')]</value>
      <webElementGuid>025efc6c-25b7-4ab7-8cf5-304daac1d652</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
