<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>div_Carriage House 6-Light Pendant - Extra _8eaa9c</name>
   <tag></tag>
   <elementGuidId>9a89287b-c57a-4d8c-a6c1-69f2f55e44f6</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>div.order-item-info-panel</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='shopping-cart-v2-root']/div/div[2]/div/div[4]/div/div[2]/div</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>.order-item-info-panel</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>40b3c3d7-9fa8-4e13-a795-e3ea14f4eaa7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>order-item-info-panel</value>
      <webElementGuid>3c41d8fc-179e-43b8-80e5-b869f4793fde</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Carriage House 6-Light Pendant - Extra LargeFinish: BrassItem #LC686In-stock Usually ships in 1-7 business days.EditRemoveSave for Later</value>
      <webElementGuid>3370f388-1ac6-4d61-8db7-fe6eaf3add8b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;shopping-cart-v2-root&quot;)/div[@class=&quot;shopping-cart-v2&quot;]/div[@class=&quot;main-panel&quot;]/div[@class=&quot;left-main-panel&quot;]/div[@class=&quot;items-container&quot;]/div[@class=&quot;order-item-display-widget-v2&quot;]/div[@class=&quot;order-item-display-wrapper&quot;]/div[@class=&quot;order-item-info-panel&quot;]</value>
      <webElementGuid>3b0bd86f-dbd7-4735-abe4-2bf41354c337</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='shopping-cart-v2-root']/div/div[2]/div/div[4]/div/div[2]/div</value>
      <webElementGuid>75a76210-9e9c-49f8-b57f-d4a9a3d98ff6</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='HURRY! GOING FAST'])[1]/following::div[2]</value>
      <webElementGuid>26d70138-77f9-484b-a8f1-7b6cb6f15426</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='shoppers'])[1]/following::div[4]</value>
      <webElementGuid>17f37e45-bdab-4c69-aa20-a787a6ed153e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[4]/div/div[2]/div</value>
      <webElementGuid>32b618fd-b290-4ad0-bae3-7135c34b2f86</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//div[(text() = 'Carriage House 6-Light Pendant - Extra LargeFinish: BrassItem #LC686In-stock Usually ships in 1-7 business days.EditRemoveSave for Later' or . = 'Carriage House 6-Light Pendant - Extra LargeFinish: BrassItem #LC686In-stock Usually ships in 1-7 business days.EditRemoveSave for Later')]</value>
      <webElementGuid>a65ef73f-5cff-4a2d-8e12-895a4dd7710d</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
