<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>div_Carriage House 6-Light Pendant - Extra _8c8b79</name>
   <tag></tag>
   <elementGuidId>2545137a-57c6-4463-ae76-8b1d8e82ff80</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>div.order-item-info-panel</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='shopping-cart-v2-root']/div/div[2]/div/div[4]/div/div/div</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>.order-item-info-panel</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>c4ecb04a-7309-4613-b93d-8019f2b93815</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>order-item-info-panel</value>
      <webElementGuid>65fb3b9e-911d-46d6-bf77-e080b0c6e03a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Carriage House 6-Light Pendant - Extra LargeFinish: Dark BronzeItem #LC686In-stock Usually ships in 1-7 business days.EditRemoveSave for Later</value>
      <webElementGuid>c8877fea-3cbb-4a7b-8e8b-c9978275dfaf</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;shopping-cart-v2-root&quot;)/div[@class=&quot;shopping-cart-v2&quot;]/div[@class=&quot;main-panel&quot;]/div[@class=&quot;left-main-panel&quot;]/div[@class=&quot;items-container&quot;]/div[@class=&quot;order-item-display-widget-v2&quot;]/div[@class=&quot;order-item-display-wrapper&quot;]/div[@class=&quot;order-item-info-panel&quot;]</value>
      <webElementGuid>ad611f51-6c6c-499e-8344-e04f4a690399</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='shopping-cart-v2-root']/div/div[2]/div/div[4]/div/div/div</value>
      <webElementGuid>b953ec31-7de8-4f16-a637-f5b7ab4033dd</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Total Price'])[1]/following::div[4]</value>
      <webElementGuid>7402290b-15d8-473d-98a7-62f417ad9218</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Quantity'])[1]/following::div[5]</value>
      <webElementGuid>1f235d77-b166-4a9c-91fd-d0d8d6f22d13</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div/div[4]/div/div/div</value>
      <webElementGuid>5e5504b1-2197-4e6f-b50f-87c0ef713a78</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//div[(text() = 'Carriage House 6-Light Pendant - Extra LargeFinish: Dark BronzeItem #LC686In-stock Usually ships in 1-7 business days.EditRemoveSave for Later' or . = 'Carriage House 6-Light Pendant - Extra LargeFinish: Dark BronzeItem #LC686In-stock Usually ships in 1-7 business days.EditRemoveSave for Later')]</value>
      <webElementGuid>419aaae9-8a54-4f06-b025-9ab4aa1b3955</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
