<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>div_Carriage House 6-Light Pendant - Extra _a3990b</name>
   <tag></tag>
   <elementGuidId>921919b6-e6fa-4ee9-8be2-df05121896ad</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>div.order-item-display-wrapper</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='shopping-cart-v2-root']/div/div[2]/div/div[4]/div/div</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>.order-item-display-wrapper</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>180bd710-dbc6-443c-a254-2e8ca76b5c70</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>order-item-display-wrapper</value>
      <webElementGuid>707d909c-ea57-497f-b064-e6c0e6b05787</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Carriage House 6-Light Pendant - Extra LargeFinish: Dark BronzeItem #LC686In-stock Usually ships in 1-7 business days.EditRemoveSave for Later$599.00$1,198.00</value>
      <webElementGuid>60a3933c-cfc2-4677-86f1-0fbf77463aa1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;shopping-cart-v2-root&quot;)/div[@class=&quot;shopping-cart-v2&quot;]/div[@class=&quot;main-panel&quot;]/div[@class=&quot;left-main-panel&quot;]/div[@class=&quot;items-container&quot;]/div[@class=&quot;order-item-display-widget-v2&quot;]/div[@class=&quot;order-item-display-wrapper&quot;]</value>
      <webElementGuid>33657620-2363-43bc-8923-fb337810ae87</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='shopping-cart-v2-root']/div/div[2]/div/div[4]/div/div</value>
      <webElementGuid>4430a927-0d83-439f-8e2e-2846423412bc</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Total Price'])[1]/following::div[3]</value>
      <webElementGuid>fd159361-3107-4d14-90b0-824ada446e5e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Quantity'])[1]/following::div[4]</value>
      <webElementGuid>7dfa172c-cd56-49bd-bf1d-61b91c5e247f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div/div[2]/div/div[4]/div/div</value>
      <webElementGuid>39c1a524-c5f7-4ab7-8081-a39192c0af45</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//div[(text() = 'Carriage House 6-Light Pendant - Extra LargeFinish: Dark BronzeItem #LC686In-stock Usually ships in 1-7 business days.EditRemoveSave for Later$599.00$1,198.00' or . = 'Carriage House 6-Light Pendant - Extra LargeFinish: Dark BronzeItem #LC686In-stock Usually ships in 1-7 business days.EditRemoveSave for Later$599.00$1,198.00')]</value>
      <webElementGuid>ae33122c-1587-42fc-813f-e8792b817ad8</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
