<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>img_Dark Bronze_gwt-image-picker-option-image</name>
   <tag></tag>
   <elementGuidId>873e2b95-ccd3-4fac-a11f-ffbeb1242412</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>div.gwt-image-picker-option > div.image-picker-option-image-container > img.gwt-image-picker-option-image</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='personalization-modal-options-scroll']/div/div[2]/div/div/div/div[3]/div/div/div/div/img</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:role=button[name=&quot;Brass&quot;i]</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>img</value>
      <webElementGuid>f587da5f-aac1-4626-9164-fe574a40af35</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>gwt-image-picker-option-image</value>
      <webElementGuid>fcf6348e-38b8-43e0-a80b-104fe62be590</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>alt</name>
      <type>Main</type>
      <value>Brass</value>
      <webElementGuid>16883ce1-5ff9-4dde-8cf1-f8d5e5f9a852</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-siid</name>
      <type>Main</type>
      <value>16</value>
      <webElementGuid>49977c97-62a5-4d45-b1bb-3b9bf2dacf11</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-mfpartnumber</name>
      <type>Main</type>
      <value>LC686</value>
      <webElementGuid>73b1ffbc-96e8-4d0a-85c4-d874dffa6905</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>color</name>
      <type>Main</type>
      <value>BRA</value>
      <webElementGuid>30638833-82ea-4d9b-a82e-58f344d8af61</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>role</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>131c60fb-4994-42d5-b672-74f7ca597dc9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-pressed</name>
      <type>Main</type>
      <value>false</value>
      <webElementGuid>8df24455-45d2-4fe3-978e-4e6e67c248e3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>src</name>
      <type>Main</type>
      <value>https://akamai-scene7.ballarddesigns.com/is/image/ballarddesigns/LC686_BRA?$w88$</value>
      <webElementGuid>f5f3b484-76d5-4c48-be99-378e54776fa2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;personalization-modal-options-scroll&quot;)/div[@class=&quot;gwt-accordion-tab first&quot;]/div[@class=&quot;gwt-accordion-tab-content tabopen&quot;]/div[1]/div[@class=&quot;gwt-personalization-modal-accordions-content&quot;]/div[@class=&quot;gwt-personalization-modal-accordions-content-option&quot;]/div[@class=&quot;gwt-product-option-panel-widget-panel&quot;]/div[@class=&quot;gwt-image-picker&quot;]/div[@class=&quot;gwt-image-picker-option-holder&quot;]/div[@class=&quot;gwt-image-picker-option&quot;]/div[@class=&quot;image-picker-option-image-container&quot;]/img[@class=&quot;gwt-image-picker-option-image&quot;]</value>
      <webElementGuid>4b55fc3d-7464-417d-b614-2d2898fa5674</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='personalization-modal-options-scroll']/div/div[2]/div/div/div/div[3]/div/div/div/div/img</value>
      <webElementGuid>20a7d7a9-de0c-48ed-8f1e-ed4d9b40e1ab</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:img</name>
      <type>Main</type>
      <value>//img[@alt='Brass']</value>
      <webElementGuid>bbaad7c9-f59a-4ec9-9e20-82e2ff3b7d83</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[3]/div/div/div/div/img</value>
      <webElementGuid>2a1da4f6-8bd5-42e9-b3ff-3171238b534e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//img[@alt = 'Brass' and @src = 'https://akamai-scene7.ballarddesigns.com/is/image/ballarddesigns/LC686_BRA?$w88$']</value>
      <webElementGuid>3f309781-8f35-4d05-808b-1616e0ba05c1</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
