<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>img_Gear Pull Brushed Nickel_gwt-image-pick_4e2018</name>
   <tag></tag>
   <elementGuidId>0ae0d900-91af-4b6b-bc79-ea4aa87513e3</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value></value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='personalization-modal-options-scroll']/div/div[2]/div/div/div/div[3]/div/div/div[3]/div/img</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:role=button[name=&quot;Rectangle Pull Antique Brass&quot;i]</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>img</value>
      <webElementGuid>ad177787-8f08-4c0f-b655-0150a730b1fd</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>gwt-image-picker-option-image</value>
      <webElementGuid>6240a2d0-e218-4bbf-ade7-7ab76ae00ab5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>alt</name>
      <type>Main</type>
      <value>Rectangle Pull Antique Brass</value>
      <webElementGuid>b776fef5-3f8e-4088-bba2-dcd8498fd387</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-siid</name>
      <type>Main</type>
      <value>17</value>
      <webElementGuid>8f20c1c2-d7bf-4831-93b1-96515a237d3d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-mfpartnumber</name>
      <type>Main</type>
      <value>MO611</value>
      <webElementGuid>d976d296-ace2-4e4f-8b9d-af3ec9fb3ee0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>color</name>
      <type>Main</type>
      <value>HDAB</value>
      <webElementGuid>71f44b7c-8804-45b4-b106-897e2b8f895b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>role</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>03a52ea1-bde6-411a-bc83-a609a58b5194</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-pressed</name>
      <type>Main</type>
      <value>false</value>
      <webElementGuid>97abc6bc-c865-4908-8e52-6faa9701d25c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>src</name>
      <type>Main</type>
      <value>https://akamai-scene7.ballarddesigns.com/is/image/ballarddesigns/MO611_HDAB?$w88$</value>
      <webElementGuid>0cc56470-9456-42de-9ed4-889b36a33d2b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;personalization-modal-options-scroll&quot;)/div[@class=&quot;gwt-accordion-tab first&quot;]/div[@class=&quot;gwt-accordion-tab-content tabopen&quot;]/div[1]/div[@class=&quot;gwt-personalization-modal-accordions-content&quot;]/div[@class=&quot;gwt-personalization-modal-accordions-content-option&quot;]/div[@class=&quot;gwt-product-option-panel-widget-panel&quot;]/div[@class=&quot;gwt-image-picker&quot;]/div[@class=&quot;gwt-image-picker-option-holder&quot;]/div[@class=&quot;gwt-image-picker-option&quot;]/div[@class=&quot;image-picker-option-image-container&quot;]/img[@class=&quot;gwt-image-picker-option-image&quot;]</value>
      <webElementGuid>a8f1b420-363b-4af3-892d-6e21c11f68cd</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='personalization-modal-options-scroll']/div/div[2]/div/div/div/div[3]/div/div/div[3]/div/img</value>
      <webElementGuid>022834a1-71b9-47a6-bcc9-880ed49988f4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:img</name>
      <type>Main</type>
      <value>//img[@alt='Rectangle Pull Antique Brass']</value>
      <webElementGuid>eafc4013-a23f-405e-86d5-07f3038786b1</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[3]/div/div/div[3]/div/img</value>
      <webElementGuid>117881cc-cf72-4356-828e-459003ecac17</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//img[@alt = 'Rectangle Pull Antique Brass' and @src = 'https://akamai-scene7.ballarddesigns.com/is/image/ballarddesigns/MO611_HDAB?$w88$']</value>
      <webElementGuid>56eef7aa-131c-4909-ba0b-0671c56371b1</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
