<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>button_Add To Cart</name>
   <tag></tag>
   <elementGuidId>a477adea-5257-4e4d-81ba-3ebea697eb76</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#gwt-add-to-cart-btn</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//button[@id='gwt-add-to-cart-btn']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>#gwt-product-detail-widget-id-13730 >> internal:role=button[name=&quot;Add To Cart&quot;i]</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>7432a12c-e3c8-4ca6-bebe-7b4a06607960</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>a9ce51b5-0ae4-41fd-bfff-6fc4c7031256</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>button primary gwt-add-to-cart-btn</value>
      <webElementGuid>72bc7caa-8bd5-4648-915f-1aa5f24e79fd</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>role</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>a6ca5d41-ac73-4dad-8a85-fe598181c24d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>gwt-add-to-cart-btn</value>
      <webElementGuid>9dca61d8-0cf5-4386-af73-d11567f57402</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>catentryid</name>
      <type>Main</type>
      <value>13730</value>
      <webElementGuid>8b7cf85b-5680-43f2-9bb3-fa1cf0bbf020</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Add To Cart</value>
      <webElementGuid>c6b51474-fdd0-4587-b4b6-3b67938703ba</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;gwt-product-detail-widget-id-13730&quot;)/div[@class=&quot;product-detail-widget-bottom-links-panel&quot;]/div[@class=&quot;qty-selector-add-to-cart-panel gwt-product-detail-widget-price-column&quot;]/button[@id=&quot;gwt-add-to-cart-btn&quot;]</value>
      <webElementGuid>be93557d-bc7b-4bda-b254-f481483c7e4f</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//button[@id='gwt-add-to-cart-btn']</value>
      <webElementGuid>0afb89b5-14e0-4f1a-bf9e-f317a56889db</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='gwt-product-detail-widget-id-13730']/div[5]/div/button</value>
      <webElementGuid>78647e9d-6356-4822-8f4d-cfe80550f0f2</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='$2,729.00'])[2]/following::button[3]</value>
      <webElementGuid>89655c03-a89d-4849-844b-a08d9292231b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Edit Selections'])[1]/following::button[3]</value>
      <webElementGuid>98040db3-c129-4f47-a239-5fcb4705f791</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='♥ Add to Wishlist or Registry'])[1]/preceding::button[1]</value>
      <webElementGuid>e8733ffa-7ef5-44cd-9565-7444d59a468c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[5]/div/button</value>
      <webElementGuid>e399c320-683b-4c82-b273-0ac310544f5f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//button[@type = 'button' and @id = 'gwt-add-to-cart-btn' and (text() = 'Add To Cart' or . = 'Add To Cart')]</value>
      <webElementGuid>9f8711e7-f4c2-4112-8e41-2125dc6f5ea5</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
