<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>button_Update Cart</name>
   <tag></tag>
   <elementGuidId>3b56e906-ccad-4fac-adae-7d7e56bd45aa</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#gwt-add-to-cart-btn</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//button[@id='gwt-add-to-cart-btn']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>#gwt-product-detail-widget-id-13730 >> internal:role=button[name=&quot;Update Cart&quot;i]</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>22533f38-3e65-42a9-b880-1ed70a24df77</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>41c83a03-9ca8-461e-8a67-63010947cb9d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>button primary gwt-update-to-cart-btn gwt-add-to-cart-btn</value>
      <webElementGuid>1b08acaf-9e38-4c5a-a1ed-9c33462da3e9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>role</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>0b462d02-289d-4b8d-885b-dca60a50ed07</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>gwt-add-to-cart-btn</value>
      <webElementGuid>afd83802-e496-4462-92c1-d1dcd3fd7898</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>catentryid</name>
      <type>Main</type>
      <value>13730</value>
      <webElementGuid>9e6e636e-83ed-4938-9668-c09d7538c993</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Update Cart</value>
      <webElementGuid>76e97ecf-de07-42c0-901d-ab1144685e22</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;gwt-product-detail-widget-id-13730&quot;)/div[@class=&quot;product-detail-widget-bottom-links-panel&quot;]/div[@class=&quot;qty-selector-add-to-cart-panel gwt-product-detail-widget-price-column&quot;]/button[@id=&quot;gwt-add-to-cart-btn&quot;]</value>
      <webElementGuid>e21714b5-6cb8-4851-aceb-cf3d43f65509</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//button[@id='gwt-add-to-cart-btn']</value>
      <webElementGuid>2ee08055-8580-4b94-8529-07710a9fc12f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='gwt-product-detail-widget-id-13730']/div[5]/div/button</value>
      <webElementGuid>7435f6f0-8407-4345-b9b0-834e148c1cb0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='$2,729.00'])[2]/following::button[3]</value>
      <webElementGuid>b5b8faf4-1448-480a-8eb9-432d89969c76</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Edit Selections'])[1]/following::button[3]</value>
      <webElementGuid>ff8068ca-2ebe-4d20-896e-d18daa2cb951</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='♥ Add to Wishlist or Registry'])[1]/preceding::button[1]</value>
      <webElementGuid>2680a80c-bb84-4443-856a-c2f904ba2101</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[5]/div/button</value>
      <webElementGuid>27086a95-c364-4396-82f2-2e596885c4e0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//button[@type = 'button' and @id = 'gwt-add-to-cart-btn' and (text() = 'Update Cart' or . = 'Update Cart')]</value>
      <webElementGuid>0046a184-b30d-47a8-a9e1-b67b0493e137</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
