<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>iframe_Your offer_fcopt-offer-68948-content</name>
   <tag></tag>
   <elementGuidId>c8890f84-4b2a-4e68-a48f-9a6289a3332e</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#fcopt-offer-68948-content</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//iframe[@id='fcopt-offer-68948-content']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>iframe[title=&quot;Welcome Dialog&quot;]</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>iframe</value>
      <webElementGuid>2c313510-c4d6-43ed-9673-f1c95e7dc741</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>fcopt-offer-68948-content</value>
      <webElementGuid>93146dd9-93bd-404d-a947-2f5d37611ed4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>frameborder</name>
      <type>Main</type>
      <value>0</value>
      <webElementGuid>c0da7156-249c-48ca-bcd4-0eaabaec9cf2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>width</name>
      <type>Main</type>
      <value>100%</value>
      <webElementGuid>02b1867d-cb81-4e73-9bcf-415a8a376ba2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>height</name>
      <type>Main</type>
      <value>100%</value>
      <webElementGuid>9cc553fd-1d51-4980-a7b0-37131df2c8de</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>scrolling</name>
      <type>Main</type>
      <value>no</value>
      <webElementGuid>68cbe160-b7be-46b5-977b-0a1045d14d57</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>title</name>
      <type>Main</type>
      <value>Welcome Dialog</value>
      <webElementGuid>a255008e-07f7-46bb-b16c-74ca9f0c7b60</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>src</name>
      <type>Main</type>
      <value>https://api.securedvisit.com/lightbox/client/1150_03659/?fp=a31b711964045d91ae28537ec0137a23&amp;m=form&amp;form_id=68948&amp;promo_id=8804&amp;v=1712575963823</value>
      <webElementGuid>4ffecc1e-8a29-4059-a47e-eb9190d0ae1d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;fcopt-offer-68948-content&quot;)</value>
      <webElementGuid>729ba3df-5fb1-4b8d-8a0a-3e802d27e95e</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//iframe[@id='fcopt-offer-68948-content']</value>
      <webElementGuid>54a0ec8a-e1ac-4eb8-aa7c-1e18980b4262</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='fcopt-onsite-app-68948_wrapper']/div[2]/div/div/iframe</value>
      <webElementGuid>137dd681-003b-44bd-9683-b0a258a5c1fc</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div/div/iframe</value>
      <webElementGuid>b7ec2687-3330-43f2-9d04-197fa98d4ba3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//iframe[@id = 'fcopt-offer-68948-content' and @title = 'Welcome Dialog' and @src = 'https://api.securedvisit.com/lightbox/client/1150_03659/?fp=a31b711964045d91ae28537ec0137a23&amp;m=form&amp;form_id=68948&amp;promo_id=8804&amp;v=1712575963823']</value>
      <webElementGuid>c0478ae5-0ca6-4840-a15b-838a10213781</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
