<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>img_Order a Swatch_gwt-image-picker-option-image</name>
   <tag></tag>
   <elementGuidId>7788302e-ce24-494e-8bc3-073c329bd4a1</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>img.gwt-image-picker-option-image</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='gwt-option-panel']/div/div[3]/div/div/div/div/img</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:role=button[name=&quot;Rubbed Black - $2,729.00&quot;i]</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>img</value>
      <webElementGuid>d92428c0-63b8-402d-a54e-6dab46f58d5d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>gwt-image-picker-option-image</value>
      <webElementGuid>b1c74658-3a1c-469e-b042-59222cc53172</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>alt</name>
      <type>Main</type>
      <value>Rubbed Black  - $2,729.00 </value>
      <webElementGuid>1fd9bc8a-2518-401a-9109-612567698509</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-siid</name>
      <type>Main</type>
      <value>7</value>
      <webElementGuid>4e9a0c89-7aa8-4641-89fa-ab549d6fe4f1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-mfpartnumber</name>
      <type>Main</type>
      <value>MO267</value>
      <webElementGuid>417ac6d7-ef40-4e68-bd58-ebba8e6d4d29</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>color</name>
      <type>Main</type>
      <value>OBL</value>
      <webElementGuid>353285b9-1c36-491d-9e39-b2bfbd3ac2e9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>role</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>503403e7-a694-42db-8db6-0b8b93595c23</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>src</name>
      <type>Main</type>
      <value>https://akamai-scene7.ballarddesigns.com/is/image/ballarddesigns/MO267_OBL?$w88$</value>
      <webElementGuid>ce89bbd7-adb1-4372-93e1-5a020c983e04</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;gwt-product-detail-widget-id-13730&quot;)/div[@class=&quot;gwt-bundle-vk-detail-widget-column3&quot;]/div[@id=&quot;gwt-option-panel&quot;]/div[@class=&quot;active enabled gwt-product-option-panel-swatchbox&quot;]/div[@class=&quot;gwt-product-option-panel-widget-panel&quot;]/div[@class=&quot;gwt-image-picker&quot;]/div[@class=&quot;gwt-image-picker-option-holder&quot;]/div[@class=&quot;gwt-image-picker-option&quot;]/div[@class=&quot;image-picker-option-image-container&quot;]/img[@class=&quot;gwt-image-picker-option-image&quot;]</value>
      <webElementGuid>5021e712-01c8-4036-a9c9-2bc9b0e36ec2</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='gwt-option-panel']/div/div[3]/div/div/div/div/img</value>
      <webElementGuid>e1c2533b-d4c3-4380-b475-680a81fa0c32</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:img</name>
      <type>Main</type>
      <value>//img[@alt='Rubbed Black  - $2,729.00 ']</value>
      <webElementGuid>a1cc82d1-94c0-4d8c-88af-c87464684418</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[4]/div/div/div[3]/div/div/div/div/img</value>
      <webElementGuid>ded920c4-e863-41e1-bbe8-2631b8948d67</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//img[@alt = 'Rubbed Black  - $2,729.00 ' and @src = 'https://akamai-scene7.ballarddesigns.com/is/image/ballarddesigns/MO267_OBL?$w88$']</value>
      <webElementGuid>01d8bf68-985f-409b-ae11-12538b7e1bda</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
