<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>img_Select Style_gwt-image-picker-option-image</name>
   <tag></tag>
   <elementGuidId>5eb14105-953e-4de3-9562-6b8d1889770c</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value></value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='gwt-option-panel']/div/div[4]/div/div/div[2]/div/img</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:role=button[name=&quot;Gear Pull Brushed Nickel&quot;i]</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>img</value>
      <webElementGuid>62cb9521-8125-4004-9cef-af916848701f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>gwt-image-picker-option-image</value>
      <webElementGuid>63e8d724-f016-4636-9b06-29cefa51a612</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>alt</name>
      <type>Main</type>
      <value>Gear Pull Brushed Nickel</value>
      <webElementGuid>26dad78e-cd90-476d-8592-50c9817f12c7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-siid</name>
      <type>Main</type>
      <value>16</value>
      <webElementGuid>c4228c97-c304-4689-8196-3d3804062f82</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-mfpartnumber</name>
      <type>Main</type>
      <value>MO611</value>
      <webElementGuid>28c682d4-605e-4f4a-b5a8-f31ec23d355f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>color</name>
      <type>Main</type>
      <value>BRBN</value>
      <webElementGuid>da465552-385f-48f9-a438-70c20843ff51</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>role</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>61267249-a7b0-4ccd-953e-9e96c2b3162a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>src</name>
      <type>Main</type>
      <value>https://akamai-scene7.ballarddesigns.com/is/image/ballarddesigns/MO611_BRBN?$w88$</value>
      <webElementGuid>f0761e97-87ce-461a-893e-8f7e90646b0b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;gwt-product-detail-widget-id-642457&quot;)/div[@class=&quot;gwt-product-detail-widget-options-column&quot;]/div[@id=&quot;gwt-option-panel&quot;]/div[@class=&quot;active enabled gwt-product-option-panel-swatchbox&quot;]/div[@class=&quot;gwt-product-option-panel-widget-panel&quot;]/div[@class=&quot;gwt-image-picker&quot;]/div[@class=&quot;gwt-image-picker-option-holder&quot;]/div[@class=&quot;gwt-image-picker-option&quot;]/div[@class=&quot;image-picker-option-image-container&quot;]/img[@class=&quot;gwt-image-picker-option-image&quot;]</value>
      <webElementGuid>907032d3-7157-4773-bd1e-cdfc102e2ef5</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='gwt-option-panel']/div/div[4]/div/div/div[2]/div/img</value>
      <webElementGuid>b32236fd-dbca-4afa-ada9-176511ce0b28</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:img</name>
      <type>Main</type>
      <value>//img[@alt='Gear Pull Brushed Nickel']</value>
      <webElementGuid>6e5d26b7-64cd-4c50-b2af-68ba300cf547</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[4]/div/div/div[2]/div/img</value>
      <webElementGuid>4b50f261-117f-4b74-8af3-ed601d391bc2</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//img[@alt = 'Gear Pull Brushed Nickel' and @src = 'https://akamai-scene7.ballarddesigns.com/is/image/ballarddesigns/MO611_BRBN?$w88$']</value>
      <webElementGuid>dad4bf3a-5854-46ef-93eb-b55286544737</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
