<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>button_In-stock usually ships in 1-7 busine_2d3f42</name>
   <tag></tag>
   <elementGuidId>9221215a-216a-41a1-9335-4c2a143f4c85</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#incrementId</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//button[@id='incrementId']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>#quantity_461340 >> internal:label=&quot;increment quantity&quot;i</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>caf3a7e9-0207-4be1-a463-96f9507aded3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>cd4e873b-de5e-4acd-8eef-568122c83ecd</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>button primary gwt-quantity-textbox-increment</value>
      <webElementGuid>93206874-a28c-4d41-a80b-88bdc3f8f526</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>role</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>f089e060-18bd-4bc2-a85a-bc954c6b7dcc</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>incrementId</value>
      <webElementGuid>634d13c8-6e20-4047-9ba9-15ae7740c386</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-label</name>
      <type>Main</type>
      <value>increment quantity</value>
      <webElementGuid>db8d1e2d-065f-4b1d-8423-6e3e8b1a5848</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;quantity_461340&quot;)/button[@id=&quot;incrementId&quot;]</value>
      <webElementGuid>5fa0fcab-b6a5-47da-aa7c-ca2c194b443c</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//button[@id='incrementId']</value>
      <webElementGuid>52ae7dac-c994-48cc-b947-64a52ef9cc26</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='quantity_461340']/button[2]</value>
      <webElementGuid>1cd1b066-fff9-4175-91ef-5741cf8df5c4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div/div/button[2]</value>
      <webElementGuid>7de132cf-5446-4b13-a529-f1fcf3a32f46</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//button[@type = 'button' and @id = 'incrementId']</value>
      <webElementGuid>b3113b07-e7ca-4025-8386-9d9697e194d4</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
