<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>button_Add To Cart</name>
   <tag></tag>
   <elementGuidId>26f2a06a-09dd-49db-9d90-59ab1cd5ebed</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#gwt-add-to-cart-btn</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//button[@id='gwt-add-to-cart-btn']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>#gwt-product-detail-widget-id-461340 >> internal:role=button[name=&quot;Add To Cart&quot;i]</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>82fc7671-5380-4540-8d68-1e034f508542</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>0f6c5d4d-f41b-464f-a6df-2bd7f532f7a0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>button primary</value>
      <webElementGuid>6c4bafd4-cd62-4d39-9884-ad236fbc878e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>role</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>633bac5c-8992-4e76-bdcd-5ec3fb868710</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>gwt-add-to-cart-btn</value>
      <webElementGuid>e65dbd36-6ee1-4efa-828b-5fc57d9caa6f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>catentryid</name>
      <type>Main</type>
      <value>461340</value>
      <webElementGuid>5c5b408e-80a2-45c8-9508-f5f3ae6afd2c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Add To Cart</value>
      <webElementGuid>eecc4543-f14e-4bc3-b73e-ae9f1fe2da51</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;gwt-product-detail-widget-id-461340&quot;)/div[@class=&quot;product-detail-widget-bottom-links-panel&quot;]/div[@class=&quot;gwt-product-detail-widget-price-column qty-selector-add-to-cart-panel&quot;]/div[@class=&quot;gwt-bundle-add-to-cart-btn&quot;]/button[@id=&quot;gwt-add-to-cart-btn&quot;]</value>
      <webElementGuid>fe6ac26b-dbdd-46a5-8dea-5921a38bc71b</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//button[@id='gwt-add-to-cart-btn']</value>
      <webElementGuid>9ccbc634-567d-42c8-a8f4-6075c3442253</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='gwt-product-detail-widget-id-461340']/div[4]/div[2]/div[2]/button</value>
      <webElementGuid>e8cce1ae-2665-4194-9c73-18329a9e20e9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='In-stock usually ships in 1-7 business days.'])[1]/following::button[3]</value>
      <webElementGuid>f2fac7e7-a5f1-4273-a6f9-36f780c40068</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='$39.00'])[1]/following::button[3]</value>
      <webElementGuid>b5eb2648-86fd-4cd3-a352-a6f1b5c77f11</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='♥ Add to Wishlist or Registry'])[1]/preceding::button[1]</value>
      <webElementGuid>754292ee-c9d3-41cb-b426-527ed082a17b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[4]/div[2]/div[2]/button</value>
      <webElementGuid>cc29bd9d-09be-479d-af54-946f809933a3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//button[@type = 'button' and @id = 'gwt-add-to-cart-btn' and (text() = 'Add To Cart' or . = 'Add To Cart')]</value>
      <webElementGuid>e05e3044-39ff-4943-9f5d-9216e045ed5b</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
