<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>div_Close_CID-7757-g-x-icon</name>
   <tag></tag>
   <elementGuidId>c85d325e-237e-4770-b123-68181e8455f0</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>div.CID-7757-g-x-icon</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='CID-7757']/div/div/div/div</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>.CID-7757-g-x-icon >> nth=0</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>e94303fa-da64-4e17-acc7-24f412def17f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>CID-7757-g-x-icon</value>
      <webElementGuid>14159841-0768-4bdf-a33c-3c0cd9f629a5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;CID-7757&quot;)/div[@class=&quot;CID-7757-granify-flex-placement CID-7757-granify-right&quot;]/div[@class=&quot;CID-7757-granify-widget-wrapper CID-7757-granify-show&quot;]/div[@class=&quot;CID-7757-granify-close-button&quot;]/div[@class=&quot;CID-7757-g-x-icon&quot;]</value>
      <webElementGuid>0b802166-2c09-4162-88c6-a473df2fc733</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='CID-7757']/div/div/div/div</value>
      <webElementGuid>85365e55-ebb1-44e7-94f0-121ef7e01d43</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[13]/div/div/div/div</value>
      <webElementGuid>2d8f8039-5c79-4afb-9dc6-0ef67e732efa</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
