<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>button_In-stock usually ships in 1-7 busine_2d3f42</name>
   <tag></tag>
   <elementGuidId>ca579ab8-bedd-4c27-ab80-625c16390154</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#incrementId</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//button[@id='incrementId']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>#quantity_232734 >> internal:label=&quot;increment quantity&quot;i</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>37dd7622-4c53-4b57-b886-7af6ff89c4ff</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>dad2b74b-304e-42d3-909c-ba572f9671e4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>button primary gwt-quantity-textbox-increment</value>
      <webElementGuid>bc6313a8-5044-4c95-acf7-282f70d65c97</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>role</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>8d23d28e-037d-433a-bda2-01a3d4cbc44e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>incrementId</value>
      <webElementGuid>9e5466b8-7f09-403b-8f1c-0f8b566f0016</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-label</name>
      <type>Main</type>
      <value>increment quantity</value>
      <webElementGuid>55d90e09-5b41-47f9-a74d-bc63bf0d9d49</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;quantity_232734&quot;)/button[@id=&quot;incrementId&quot;]</value>
      <webElementGuid>606d3567-25e0-4f0e-b52c-8f234a90bfc0</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//button[@id='incrementId']</value>
      <webElementGuid>42a9ff1e-f22d-4c03-a5cd-40d0bd478865</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='quantity_232734']/button[2]</value>
      <webElementGuid>3b7326fd-bd1d-423f-8b70-0252d73d3ec5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div/div/button[2]</value>
      <webElementGuid>5853b5b8-af93-4681-a2b3-c72c6ca0a089</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//button[@type = 'button' and @id = 'incrementId']</value>
      <webElementGuid>bd62709a-3b6a-44f6-807f-89c714389919</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
