<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>button_Add To Cart</name>
   <tag></tag>
   <elementGuidId>3b08e858-5cba-48f8-89cc-c1ceeb34326f</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#gwt-add-to-cart-btn</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//button[@id='gwt-add-to-cart-btn']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>#gwt-product-detail-widget-id-232734 >> internal:role=button[name=&quot;Add To Cart&quot;i]</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>745794b7-6c91-4dc3-950b-d8e5f1bd21a8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>8cea5033-a8a6-4617-a087-e86589159b00</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>button primary</value>
      <webElementGuid>0b38c556-56b2-4879-9131-fd3c1e9fdadc</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>role</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>54f835c4-54ee-4d87-915d-331f6e9340e3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>gwt-add-to-cart-btn</value>
      <webElementGuid>2329edea-4149-42eb-8bb2-122a54963a93</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>catentryid</name>
      <type>Main</type>
      <value>232734</value>
      <webElementGuid>64c1c785-aa6c-4810-914e-0afb3b7e6afb</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Add To Cart</value>
      <webElementGuid>fb2fa35c-81d3-4d65-a487-aeba11e1f7b6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;gwt-product-detail-widget-id-232734&quot;)/div[@class=&quot;product-detail-widget-bottom-links-panel&quot;]/div[@class=&quot;gwt-product-detail-widget-price-column qty-selector-add-to-cart-panel&quot;]/div[@class=&quot;gwt-bundle-add-to-cart-btn&quot;]/button[@id=&quot;gwt-add-to-cart-btn&quot;]</value>
      <webElementGuid>14b733f2-7e8d-4441-beeb-619075d6f873</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//button[@id='gwt-add-to-cart-btn']</value>
      <webElementGuid>396c1bb2-337d-4d4d-93ba-25994899a4fa</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='gwt-product-detail-widget-id-232734']/div[5]/div[2]/div[2]/button</value>
      <webElementGuid>c3b6c103-c8ee-4de0-bce5-975ca045e7f4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='In-stock usually ships in 1-7 business days.'])[1]/following::button[3]</value>
      <webElementGuid>72c093cb-fd35-4e45-8f71-951b33fef6d8</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Availability:'])[1]/following::button[3]</value>
      <webElementGuid>015ce28a-8e64-41ea-aac8-a850e15f9b21</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='♥ Add to Wishlist or Registry'])[1]/preceding::button[1]</value>
      <webElementGuid>9a9925af-0241-415a-ae47-66f7990fc880</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[5]/div[2]/div[2]/button</value>
      <webElementGuid>76803180-5e93-4305-82f9-2db5f96e7daf</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//button[@type = 'button' and @id = 'gwt-add-to-cart-btn' and (text() = 'Add To Cart' or . = 'Add To Cart')]</value>
      <webElementGuid>bbfa7297-5144-46e6-be45-27f35df7a15b</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
