<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>div_Cart (2 items)2Shopping Cart 2 items</name>
   <tag></tag>
   <elementGuidId>cc960302-a92d-4690-ae3d-0aa814f171a1</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>div.mini-cart-link-inactive</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='gwt_minicart_div']/table/tbody/tr/td[2]/div</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:role=button[name=&quot; Shopping Cart 2 items&quot;i]</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>a2b2b808-feb2-45c2-abc2-7a44c03deb93</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>mini-cart-link-inactive</value>
      <webElementGuid>1d58fd7e-1308-42ca-b014-9a9e162c0882</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>role</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>e852e66b-5050-4856-96ed-818ab8efdf9e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tabindex</name>
      <type>Main</type>
      <value>0</value>
      <webElementGuid>da3faf0f-823e-4782-a0cb-125eba90f5ca</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Cart (2 items)2Shopping Cart 2 items</value>
      <webElementGuid>ca46b3ce-4850-4d68-89b3-a13c33e8bbdf</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;gwt_minicart_div&quot;)/table[1]/tbody[1]/tr[1]/td[2]/div[@class=&quot;mini-cart-link-inactive&quot;]</value>
      <webElementGuid>e4f0244d-618a-4b3f-ba42-c4f9991f0aba</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='gwt_minicart_div']/table/tbody/tr/td[2]/div</value>
      <webElementGuid>863876e9-f321-451b-a09f-d623e6026eb2</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Order Status'])[1]/following::div[3]</value>
      <webElementGuid>63485749-2e26-492e-ad2b-c798699e2fa0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Wish List'])[1]/following::div[4]</value>
      <webElementGuid>36a545a4-8529-4d89-b6fa-61cfe6ebd6a7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Gift Registry'])[1]/preceding::div[4]</value>
      <webElementGuid>7a0bf8b8-0481-4da4-954d-887611b3a6fd</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//td[2]/div</value>
      <webElementGuid>83fd58fc-1a6c-4384-b14b-2e4b5439c196</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//div[(text() = 'Cart (2 items)2Shopping Cart 2 items' or . = 'Cart (2 items)2Shopping Cart 2 items')]</value>
      <webElementGuid>3a5f25b9-b237-473a-bcd2-3cfeb067f7f2</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
