<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>img_Select Finish_gwt-image-picker-option-image</name>
   <tag></tag>
   <elementGuidId>bdb7fdbb-0f2d-438b-b417-884c4d0573af</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value></value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='gwt-option-panel']/div/div[4]/div/div/div[2]/div/img</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>#gwt-product-detail-widget-id-232734 >> internal:role=button[name=&quot;Dark Bronze&quot;i]</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>img</value>
      <webElementGuid>4e40c1d4-9399-4fb0-99b0-99475fd9e826</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>gwt-image-picker-option-image</value>
      <webElementGuid>4fb9a824-a73e-4629-92dd-17a9e2118d18</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>alt</name>
      <type>Main</type>
      <value>Dark Bronze</value>
      <webElementGuid>287459fa-a856-416a-9b1c-af9cf749d31b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-siid</name>
      <type>Main</type>
      <value>9</value>
      <webElementGuid>b1c6a645-8e5f-4eca-b4e3-1ced36aed207</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-mfpartnumber</name>
      <type>Main</type>
      <value>LC686</value>
      <webElementGuid>9b70725e-a4da-48f3-ae71-f3953485dc99</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>color</name>
      <type>Main</type>
      <value>BRZ</value>
      <webElementGuid>55ac81ed-a908-40f9-808e-a45b8ec70bc7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>role</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>0e9d4919-a87a-4568-af82-7fc8ddabf6e7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>src</name>
      <type>Main</type>
      <value>https://akamai-scene7.ballarddesigns.com/is/image/ballarddesigns/LC686_BRZ?$w88$</value>
      <webElementGuid>71dcb65e-72d8-4fd1-810a-62a8d684b6fe</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;gwt-product-detail-widget-id-232734&quot;)/div[@class=&quot;gwt-product-detail-widget-options-column&quot;]/div[@id=&quot;gwt-option-panel&quot;]/div[@class=&quot;active enabled gwt-product-option-panel-swatchbox&quot;]/div[@class=&quot;gwt-product-option-panel-widget-panel&quot;]/div[@class=&quot;gwt-image-picker&quot;]/div[@class=&quot;gwt-image-picker-option-holder&quot;]/div[@class=&quot;gwt-image-picker-option&quot;]/div[@class=&quot;image-picker-option-image-container&quot;]/img[@class=&quot;gwt-image-picker-option-image&quot;]</value>
      <webElementGuid>54074be2-5c53-43e3-b442-ed1a8ab2dd21</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='gwt-option-panel']/div/div[4]/div/div/div[2]/div/img</value>
      <webElementGuid>c7c1ddcd-a8ed-4756-9b70-c72382a3927a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:img</name>
      <type>Main</type>
      <value>//img[@alt='Dark Bronze']</value>
      <webElementGuid>d9f16949-2158-4b79-ade6-c08dcdeac157</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[4]/div/div/div[2]/div/img</value>
      <webElementGuid>143a00b1-0296-4ed5-9f09-00821ee47c61</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//img[@alt = 'Dark Bronze' and @src = 'https://akamai-scene7.ballarddesigns.com/is/image/ballarddesigns/LC686_BRZ?$w88$']</value>
      <webElementGuid>2e2333e7-1c23-4c7b-a727-f2777b64acba</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
