<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>iframe_Your offer_fcopt-offer-68948-content</name>
   <tag></tag>
   <elementGuidId>2e8df844-51c9-4ffb-a8df-105350321638</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#fcopt-offer-68948-content</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//iframe[@id='fcopt-offer-68948-content']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>iframe[title=&quot;Welcome Dialog&quot;]</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>iframe</value>
      <webElementGuid>3db3ff0b-bc00-4a86-9f32-50fbc486b288</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>fcopt-offer-68948-content</value>
      <webElementGuid>bf25c5b4-86aa-45af-ae8b-89399c2c7e3f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>frameborder</name>
      <type>Main</type>
      <value>0</value>
      <webElementGuid>fffefdde-4681-4832-9900-ff01e1041441</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>width</name>
      <type>Main</type>
      <value>100%</value>
      <webElementGuid>9cb6d342-a88a-4782-a788-98f1f63ac3d8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>height</name>
      <type>Main</type>
      <value>100%</value>
      <webElementGuid>2ca313ef-07fa-46a6-b946-a07f1247a4c7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>scrolling</name>
      <type>Main</type>
      <value>no</value>
      <webElementGuid>5753c6d0-efb3-4258-accf-6bb0981ca85e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>title</name>
      <type>Main</type>
      <value>Welcome Dialog</value>
      <webElementGuid>8b2ca983-e696-4382-9e2b-76d9645ff337</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>src</name>
      <type>Main</type>
      <value>https://api.securedvisit.com/lightbox/client/1150_03659/?fp=77898046fc6efea6398ec621e2e2c26d&amp;m=form&amp;form_id=68948&amp;promo_id=8804&amp;v=1712574971292</value>
      <webElementGuid>db0405eb-640b-4d09-a043-6c3aa81dd5b2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;fcopt-offer-68948-content&quot;)</value>
      <webElementGuid>7d9c408b-0970-4cae-b77d-4208da48d0ca</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//iframe[@id='fcopt-offer-68948-content']</value>
      <webElementGuid>728439d2-8885-49b9-9d8b-ac5254862cc2</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='fcopt-onsite-app-68948_wrapper']/div[2]/div/div/iframe</value>
      <webElementGuid>eb7de06a-9175-4b9c-b36a-9285f76369ab</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div/div/iframe</value>
      <webElementGuid>e4414dd2-a892-4dd6-a1ba-02a865e80297</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//iframe[@id = 'fcopt-offer-68948-content' and @title = 'Welcome Dialog' and @src = 'https://api.securedvisit.com/lightbox/client/1150_03659/?fp=77898046fc6efea6398ec621e2e2c26d&amp;m=form&amp;form_id=68948&amp;promo_id=8804&amp;v=1712574971292']</value>
      <webElementGuid>b11e1cc4-efb9-4d6f-bd54-0ed4c9034d96</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
