<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>img_1,227.00 - 1,699.00_gwt-image-picker-op_170771</name>
   <tag></tag>
   <elementGuidId>5c17841f-4192-42d9-87d2-ad52aa3b662e</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value></value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='gwt-option-panel']/div/div[4]/div/div/div[2]/div/img</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:role=button[name=&quot;Antique Mirror - $1,227.00&quot;i]</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>img</value>
      <webElementGuid>10eb7fe4-9cb2-4f1e-8b25-cff2ed55db8e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>gwt-image-picker-option-image</value>
      <webElementGuid>ae012282-9174-4ec3-9588-92f98043fe93</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>alt</name>
      <type>Main</type>
      <value>Antique Mirror  - $1,227.00 </value>
      <webElementGuid>ebecf258-65fc-48ab-bb9a-afe31aeb7282</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-siid</name>
      <type>Main</type>
      <value>6</value>
      <webElementGuid>b984e8d6-1172-481d-ae72-70798525fc46</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-mfpartnumber</name>
      <type>Main</type>
      <value>MO567</value>
      <webElementGuid>b1602832-7f34-4d4f-88e9-35198b7bbcc0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>color</name>
      <type>Main</type>
      <value>MIR</value>
      <webElementGuid>37b86575-771c-4d16-9b98-27cdcb375bad</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>role</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>182d012b-5fb1-4d01-8baf-e5ad72ba9903</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>src</name>
      <type>Main</type>
      <value>https://akamai-scene7.ballarddesigns.com/is/image/ballarddesigns/MO567_MIR?$w88$</value>
      <webElementGuid>98ff6e98-4e86-4323-b865-73e62f6849b4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;gwt-option-panel&quot;)/div[@class=&quot;active enabled gwt-product-option-panel-swatchbox&quot;]/div[@class=&quot;gwt-product-option-panel-widget-panel&quot;]/div[@class=&quot;gwt-image-picker&quot;]/div[@class=&quot;gwt-image-picker-option-holder&quot;]/div[@class=&quot;gwt-image-picker-option&quot;]/div[@class=&quot;image-picker-option-image-container&quot;]/img[@class=&quot;gwt-image-picker-option-image&quot;]</value>
      <webElementGuid>caf3b6f5-b9e5-44e3-a292-b15b594cca9f</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='gwt-option-panel']/div/div[4]/div/div/div[2]/div/img</value>
      <webElementGuid>6c774691-18d9-496f-ad29-ea28b11dd5e3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:img</name>
      <type>Main</type>
      <value>//img[@alt='Antique Mirror  - $1,227.00 ']</value>
      <webElementGuid>8d552972-b9f7-4ff3-b7a8-facb5a878565</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[4]/div/div/div[2]/div/img</value>
      <webElementGuid>e4f1fd23-14d1-46d1-b535-dcb434486f65</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//img[@alt = 'Antique Mirror  - $1,227.00 ' and @src = 'https://akamai-scene7.ballarddesigns.com/is/image/ballarddesigns/MO567_MIR?$w88$']</value>
      <webElementGuid>477b324b-06dd-4707-96fc-1700c27d4c9b</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
