<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>img_In-stock usually ships in 1-7 business _d8e2a1</name>
   <tag></tag>
   <elementGuidId>b97d24d5-feb7-46ac-a8bf-03dd3992970d</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value></value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='scrollableRigthPanel']/div[5]/div/div/div/div/div[2]/div[2]/div/div/div/div/div/div[4]/div/img</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:role=button[name=&quot;4-Drawer Cabinet&quot;i]</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>img</value>
      <webElementGuid>a1eddac0-d173-4548-844a-2e184367255e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>gwt-image-picker-option-image</value>
      <webElementGuid>21201086-2c0e-4e5a-9318-63eedae3ed30</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>alt</name>
      <type>Main</type>
      <value>4-Drawer Cabinet</value>
      <webElementGuid>978401e6-1cdb-4182-9172-891a39330502</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-siid</name>
      <type>Main</type>
      <value>119</value>
      <webElementGuid>da9fa907-0286-4b01-9443-a15208fc3a6c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>src</name>
      <type>Main</type>
      <value>https://akamai-scene7.ballarddesigns.com/is/image/ballarddesigns/MO570_4DWMIR?$ColorChipLargerView$</value>
      <webElementGuid>d25c813e-e9f9-432e-8147-57a7e1fd986b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-mfpartnumber</name>
      <type>Main</type>
      <value>MO570 4DW MIR</value>
      <webElementGuid>ea73deea-6740-4c29-bfcb-99c39fdb91df</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>color</name>
      <type>Main</type>
      <value>679064</value>
      <webElementGuid>e73cb6ae-dae8-480c-b6c8-1921eac17b4d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>role</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>3e3ce7ae-d2c0-459e-90f3-e0b26b96d0ce</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-pressed</name>
      <type>Main</type>
      <value>false</value>
      <webElementGuid>5389b261-449c-4352-8931-f0423cf08145</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;scrollableRigthPanel&quot;)/div[@class=&quot;vk-product-detail-accordion-container&quot;]/div[@class=&quot;vk-product-detail-accordion-panel&quot;]/div[@class=&quot;vk-product-detail-display-accordion-container&quot;]/div[@class=&quot;gwt-vk-item-display-panel&quot;]/div[@class=&quot;gwt-accordion vk-product-detail-items-display-accordion tabopen&quot;]/div[@class=&quot;gwt-accordion-tab&quot;]/div[@class=&quot;gwt-accordion-tab-content tabopen&quot;]/div[1]/div[@class=&quot;gwt-vk-item-panel&quot;]/div[@class=&quot;gwt-vk-item-panel-column3&quot;]/div[@class=&quot;gwt-image-picker&quot;]/div[@class=&quot;gwt-image-picker-option-holder&quot;]/div[@class=&quot;gwt-image-picker-option&quot;]/div[@class=&quot;image-picker-option-image-container&quot;]/img[@class=&quot;gwt-image-picker-option-image&quot;]</value>
      <webElementGuid>0a2e38db-37a7-497f-a1de-a791fa86e20f</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='scrollableRigthPanel']/div[5]/div/div/div/div/div[2]/div[2]/div/div/div/div/div/div[4]/div/img</value>
      <webElementGuid>80e9e05a-cdc5-43b8-9d23-cff08c7efed0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:img</name>
      <type>Main</type>
      <value>(//img[@alt='4-Drawer Cabinet'])[2]</value>
      <webElementGuid>93cb573a-d331-431a-9b84-45fecd5c59f3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div[2]/div/div/div/div/div/div[4]/div/img</value>
      <webElementGuid>85d615c6-6f71-44e1-af1f-61a0537d7bd4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//img[@alt = '4-Drawer Cabinet' and @src = 'https://akamai-scene7.ballarddesigns.com/is/image/ballarddesigns/MO570_4DWMIR?$ColorChipLargerView$']</value>
      <webElementGuid>a2e8a02b-c36b-47a4-bb6b-b6bb114c0203</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
