<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>img_In-stock usually ships in 1-7 business _d8e2a1_1</name>
   <tag></tag>
   <elementGuidId>c4f78a12-0890-40d7-bcd9-c9ca4c293ba5</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value></value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='scrollableRigthPanel']/div[5]/div/div/div/div/div/div[2]/div/div/div/div/div/div[5]/div/img</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:role=button[name=&quot;Cabinet with Door&quot;i]</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>img</value>
      <webElementGuid>14790575-49e2-4d90-a95a-7d47d31e1ec9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>gwt-image-picker-option-image</value>
      <webElementGuid>ed1fcb21-e9a8-4cb2-b75b-1263376b1312</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>alt</name>
      <type>Main</type>
      <value>Cabinet with Door</value>
      <webElementGuid>2d2d9d21-effc-4c55-b903-d59311cf8381</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-siid</name>
      <type>Main</type>
      <value>168</value>
      <webElementGuid>de6e7907-7c6c-40a4-94a0-34f552e6a16c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>src</name>
      <type>Main</type>
      <value>https://akamai-scene7.ballarddesigns.com/is/image/ballarddesigns/MO570_OSGMIR?$ColorChipLargerView$</value>
      <webElementGuid>d4c019bc-8b78-43eb-b167-31b8745a2c1b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-mfpartnumber</name>
      <type>Main</type>
      <value>MO570 OSG MIR</value>
      <webElementGuid>531b4340-6ed1-47a6-8de9-b044dd545279</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>color</name>
      <type>Main</type>
      <value>679066</value>
      <webElementGuid>08bf0d5d-b11a-43bf-90ba-14f89597b60c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>role</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>89bbb336-ae96-45e7-9772-61beb77e324f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-pressed</name>
      <type>Main</type>
      <value>false</value>
      <webElementGuid>8023bca9-0555-4a24-bbaf-929dff4cc309</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;scrollableRigthPanel&quot;)/div[@class=&quot;vk-product-detail-accordion-container&quot;]/div[@class=&quot;vk-product-detail-accordion-panel&quot;]/div[@class=&quot;vk-product-detail-display-accordion-container&quot;]/div[@class=&quot;gwt-vk-item-display-panel&quot;]/div[@class=&quot;gwt-accordion vk-product-detail-items-display-accordion tabopen&quot;]/div[@class=&quot;gwt-accordion-tab first&quot;]/div[@class=&quot;gwt-accordion-tab-content tabopen&quot;]/div[1]/div[@class=&quot;gwt-vk-item-panel&quot;]/div[@class=&quot;gwt-vk-item-panel-column3&quot;]/div[@class=&quot;gwt-image-picker&quot;]/div[@class=&quot;gwt-image-picker-option-holder&quot;]/div[@class=&quot;gwt-image-picker-option&quot;]/div[@class=&quot;image-picker-option-image-container&quot;]/img[@class=&quot;gwt-image-picker-option-image&quot;]</value>
      <webElementGuid>39fd5db8-6877-4aa6-83d4-8fc6b3443092</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='scrollableRigthPanel']/div[5]/div/div/div/div/div/div[2]/div/div/div/div/div/div[5]/div/img</value>
      <webElementGuid>5b37e8ec-18c0-4419-8dca-1507930ccebf</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:img</name>
      <type>Main</type>
      <value>//img[@alt='Cabinet with Door']</value>
      <webElementGuid>1e3855c0-8aa6-4d21-a237-ac6ad7a82efb</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div/div/div/div/div/div[5]/div/img</value>
      <webElementGuid>5283886e-adb3-4841-8407-a44b7f3e4456</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//img[@alt = 'Cabinet with Door' and @src = 'https://akamai-scene7.ballarddesigns.com/is/image/ballarddesigns/MO570_OSGMIR?$ColorChipLargerView$']</value>
      <webElementGuid>831cb403-e8a7-4c55-aac6-a1a9eacc4c2d</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
