<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>img_Make a Selection_gwt-image-picker-option-image_1</name>
   <tag></tag>
   <elementGuidId>756eb51f-1229-457f-ba0b-58b78057cd99</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value></value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='scrollableRigthPanel']/div[5]/div/div/div/div/div[2]/div[2]/div/div/div/div/div/div[2]/div/img</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:role=button[name=&quot;3-Drawer Cabinet&quot;i]</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>img</value>
      <webElementGuid>6589d5b7-3e11-49f3-b4a5-7b8dda38e745</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>gwt-image-picker-option-image</value>
      <webElementGuid>75564d9e-c2f7-44d8-979a-913c76a55de6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>alt</name>
      <type>Main</type>
      <value>3-Drawer Cabinet</value>
      <webElementGuid>261d5264-991c-4b37-848b-8c717bbef28b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-siid</name>
      <type>Main</type>
      <value>128</value>
      <webElementGuid>a5d9a846-7add-4138-b9fd-c77c1e3f5aa8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>src</name>
      <type>Main</type>
      <value>https://akamai-scene7.ballarddesigns.com/is/image/ballarddesigns/MO570_3DWMIR?$ColorChipLargerView$</value>
      <webElementGuid>5004834e-2685-4288-aa97-5a7ce19bcc1a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-mfpartnumber</name>
      <type>Main</type>
      <value>MO570 3DW MIR</value>
      <webElementGuid>aaba10a5-51ef-4455-8438-9e5bd57b68a8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>color</name>
      <type>Main</type>
      <value>679063</value>
      <webElementGuid>3c9ac1ed-3349-44d8-beae-f5aaa20da661</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>role</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>561bf3a7-7487-49cb-98ed-1ea08b8f4e65</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;scrollableRigthPanel&quot;)/div[@class=&quot;vk-product-detail-accordion-container&quot;]/div[@class=&quot;vk-product-detail-accordion-panel&quot;]/div[@class=&quot;vk-product-detail-display-accordion-container&quot;]/div[@class=&quot;gwt-vk-item-display-panel&quot;]/div[@class=&quot;gwt-accordion vk-product-detail-items-display-accordion tabopen&quot;]/div[@class=&quot;gwt-accordion-tab&quot;]/div[@class=&quot;gwt-accordion-tab-content tabopen&quot;]/div[1]/div[@class=&quot;gwt-vk-item-panel&quot;]/div[@class=&quot;gwt-vk-item-panel-column3&quot;]/div[@class=&quot;gwt-image-picker&quot;]/div[@class=&quot;gwt-image-picker-option-holder&quot;]/div[@class=&quot;gwt-image-picker-option&quot;]/div[@class=&quot;image-picker-option-image-container&quot;]/img[@class=&quot;gwt-image-picker-option-image&quot;]</value>
      <webElementGuid>e856255a-c801-4d21-b4e8-90185c919e95</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='scrollableRigthPanel']/div[5]/div/div/div/div/div[2]/div[2]/div/div/div/div/div/div[2]/div/img</value>
      <webElementGuid>be9b2d7c-9845-4e77-a1f4-05c68a3e3b4c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:img</name>
      <type>Main</type>
      <value>(//img[@alt='3-Drawer Cabinet'])[2]</value>
      <webElementGuid>e2cf2c8a-cd1f-46e9-99aa-527d0ec7a135</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div[2]/div/div/div/div/div/div[2]/div/img</value>
      <webElementGuid>5778adff-3bdc-4668-b833-5a74d2b7a4f2</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//img[@alt = '3-Drawer Cabinet' and @src = 'https://akamai-scene7.ballarddesigns.com/is/image/ballarddesigns/MO570_3DWMIR?$ColorChipLargerView$']</value>
      <webElementGuid>20e05371-3755-4dce-b5b9-90b2c8e141e9</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
