<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>img_View_unbxd-grid-product-image</name>
   <tag></tag>
   <elementGuidId>fe7a52fd-0417-4719-8a9a-608e11434a5f</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>img.unbxd-grid-product-image</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='unbxd-index-0']/div/div/a/img</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:role=link[name=&quot;Oval Back Louis XVI Side Chair&quot;i] >> nth=0</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>img</value>
      <webElementGuid>bc31a4af-3b26-404e-b67f-e2a3bfaaa553</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>unbxd-grid-product-image</value>
      <webElementGuid>389ef6be-3f42-46e3-81b3-b85b70fc6d0e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>alt</name>
      <type>Main</type>
      <value>Oval Back Louis XVI Side Chair</value>
      <webElementGuid>5885ddc7-defe-4439-bb8a-d474aee697c5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-siid</name>
      <type>Main</type>
      <value>9</value>
      <webElementGuid>a8157973-ff04-4609-941e-5961c202facb</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>title</name>
      <type>Main</type>
      <value>Oval Back Louis XVI Side Chair</value>
      <webElementGuid>92e95549-8ffe-4cd1-a671-25a5d4705e3b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-alternative</name>
      <type>Main</type>
      <value>https://akamai-scene7.ballarddesigns.com/is/image/ballarddesigns/T_WithoutZoom?$SLI_LargeGrid$&amp;$src=UD094_alt1&amp;$SLI_LargeGrid$&amp;defaultImage=UD094_main</value>
      <webElementGuid>7960a39a-b770-411e-8b74-d223cf821b1c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-mainimage</name>
      <type>Main</type>
      <value>https://akamai-scene7.ballarddesigns.com/is/image/ballarddesigns/T_WithoutZoom?$SLI_LargeGrid$&amp;$src=UD094_main&amp;defaultImage=UD094_main</value>
      <webElementGuid>a47f9265-c25f-466c-900f-0e030a2f85ea</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>src</name>
      <type>Main</type>
      <value>https://akamai-scene7.ballarddesigns.com/is/image/ballarddesigns/T_WithoutZoom?$SLI_LargeGrid$&amp;$src=UD094_alt1&amp;$SLI_LargeGrid$&amp;defaultImage=UD094_main</value>
      <webElementGuid>1590573b-50a1-4b5d-8446-763c3f73ee10</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;unbxd-index-0&quot;)/div[1]/div[@class=&quot;gwt-product-info-panel-image-container&quot;]/a[@class=&quot;gwt-Anchor&quot;]/img[@class=&quot;unbxd-grid-product-image&quot;]</value>
      <webElementGuid>913feb6a-0eb9-4b3e-bbe1-f7a0211b0f5c</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='unbxd-index-0']/div/div/a/img</value>
      <webElementGuid>e71142d2-23d7-48cb-84be-4acf9ae262c6</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:img</name>
      <type>Main</type>
      <value>//img[@alt='Oval Back Louis XVI Side Chair']</value>
      <webElementGuid>dcd2a2f3-53e5-4f27-91d2-b2caa91b0a6a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[7]/div/div/div/div/a/img</value>
      <webElementGuid>d3976788-9086-4f7f-aab4-8f24763d75c8</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//img[@alt = 'Oval Back Louis XVI Side Chair' and @title = 'Oval Back Louis XVI Side Chair' and @src = 'https://akamai-scene7.ballarddesigns.com/is/image/ballarddesigns/T_WithoutZoom?$SLI_LargeGrid$&amp;$src=UD094_alt1&amp;$SLI_LargeGrid$&amp;defaultImage=UD094_main']</value>
      <webElementGuid>0431ac2e-3ce8-428d-adca-f6281cc92fd0</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
