<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>div_You have added a swatch of 0 to your ca_d1d72d</name>
   <tag></tag>
   <elementGuidId>a2aefee5-362e-45f9-8c15-68b4671a19cb</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#gwt_comshop_main_pdp</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='gwt_comshop_main_pdp']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>#gwt_comshop_main_pdp</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>768ee200-91f2-415f-93c3-09d57b373f3d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>gwt_comshop_main_pdp</value>
      <webElementGuid>3391e104-b77d-45cd-a9be-6a66bf019e7c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>store</value>
      <webElementGuid>48b8f578-a39f-425f-ae86-f2c92ea69247</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;gwt_comshop_main_pdp&quot;)</value>
      <webElementGuid>8d7ece22-627b-4883-9c9b-71deb6a36c63</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//div[@id='gwt_comshop_main_pdp']</value>
      <webElementGuid>d4fe6e68-2274-4403-8d58-9608e73abc13</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//main[@id='mainContent']/div[22]</value>
      <webElementGuid>e2683a9f-3822-43c2-86fd-80a3435edfc5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[22]</value>
      <webElementGuid>bc1c63f1-250d-4a58-ae90-d5594b1a4fff</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//div[@id = 'gwt_comshop_main_pdp']</value>
      <webElementGuid>be700202-e837-4149-bbc4-fc4619b1e75d</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
