<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>img_Select Finish_gwt-pdp-swatch-thumbnail-_1f114e</name>
   <tag></tag>
   <elementGuidId>c066cf6c-23c2-47c7-b291-3f142ab2dba9</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='gwt-comshop-customization-sub-tab-panel']/table[2]/tbody/tr[2]/td/div/div/table/tbody/tr[2]/td/div/div/img</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>img.gwt-pdp-swatch-thumbnail-image.gwt-comshop-body-option-swatch</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:role=cell[name=&quot;Fossil Fossil&quot;s] >> internal:attr=[alt=&quot;Fossil&quot;i]</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>img</value>
      <webElementGuid>bb70edff-35aa-4aca-8f53-0d7e8b31cf34</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>gwt-pdp-swatch-thumbnail-image gwt-comshop-body-option-swatch</value>
      <webElementGuid>bdaae635-75de-4eca-94ea-173c1e867ff6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>alt</name>
      <type>Main</type>
      <value>Fossil</value>
      <webElementGuid>88313372-e3d8-4ad1-be86-70699a8a4424</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-siid</name>
      <type>Main</type>
      <value>24</value>
      <webElementGuid>b52c13a5-3c87-41ff-86fd-35f3e88c8b66</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tabindex</name>
      <type>Main</type>
      <value>0</value>
      <webElementGuid>90e2b04a-9499-4ba9-acd0-eb5e993d9272</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>src</name>
      <type>Main</type>
      <value>https://akamai-scene7.ballarddesigns.com/is/image/ballarddesigns//MCOM007FOS?$wcom$</value>
      <webElementGuid>c436d493-fb47-4c1a-97f4-9d492ddccf6b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;gwt-comshop-customization-sub-tab-panel&quot;)/table[2]/tbody[1]/tr[2]/td[1]/div[@class=&quot;gwt-com-shop-option-panel gwt-com-shop-first-option-panel&quot;]/div[1]/table[1]/tbody[1]/tr[2]/td[1]/div[@class=&quot;gwt-comshop-body-option-image-panel&quot;]/div[@class=&quot;gwt-comshop-body-option-swatch-container&quot;]/img[@class=&quot;gwt-pdp-swatch-thumbnail-image gwt-comshop-body-option-swatch&quot;]</value>
      <webElementGuid>f09f9a96-99b2-4364-83ef-2dd48bafafee</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='gwt-comshop-customization-sub-tab-panel']/table[2]/tbody/tr[2]/td/div/div/table/tbody/tr[2]/td/div/div/img</value>
      <webElementGuid>ad0bbe18-0090-472b-8dfb-1ca572f9464e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:img</name>
      <type>Main</type>
      <value>//img[@alt='Fossil']</value>
      <webElementGuid>21de702d-45f1-4fcb-9dda-d23352593dc1</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//td/div/div/img</value>
      <webElementGuid>46dc6131-ec85-4c3e-9b4e-03a2e73eea20</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//img[@alt = 'Fossil' and @src = 'https://akamai-scene7.ballarddesigns.com/is/image/ballarddesigns//MCOM007FOS?$wcom$']</value>
      <webElementGuid>10188f5b-2686-4afb-9d4d-ed5be2836deb</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
