<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>img_For fabric names and description hold m_191161</name>
   <tag></tag>
   <elementGuidId>04215dd6-b7fb-4206-a067-09faabec93c2</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='gwt-comshop-customization-sub-tab-panel']/table/tbody/tr[2]/td/div/div/table/tbody/tr[3]/td/table/tbody/tr[2]/td[2]/table/tbody/tr/td/div/img</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>td:nth-of-type(2) > table.gwt-comshop-fabric-image-panel > tbody > tr > td > div.gwt-PDP-Fabric-Image-panel > img.gwt-pdp-swatch-thumbnail-image</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:role=img[name=&quot;Betty Floral Multi&quot;i]</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>img</value>
      <webElementGuid>337261a8-9c4b-4edf-aa60-bf07423d4730</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>gwt-pdp-swatch-thumbnail-image</value>
      <webElementGuid>dc813365-a076-4e6a-8dae-ded39e09bcae</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>alt</name>
      <type>Main</type>
      <value>Betty Floral Multi                                                                                                              </value>
      <webElementGuid>3197e4fb-4771-4c6d-843d-9498aaaa628e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-siid</name>
      <type>Main</type>
      <value>7</value>
      <webElementGuid>804456ef-28d2-49d9-aa80-d013fb813e7d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tabindex</name>
      <type>Main</type>
      <value>0</value>
      <webElementGuid>2c2603a9-8982-4f0c-9ec0-52846303e036</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>title</name>
      <type>Main</type>
      <value>Betty Floral Multi                                                                                                              </value>
      <webElementGuid>30ecc767-0737-4950-b388-c34467393c79</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>src</name>
      <type>Main</type>
      <value>https://akamai-scene7.ballarddesigns.com/is/image/ballarddesigns//BFM?$wcom$</value>
      <webElementGuid>cea8d748-2089-49da-af43-d6d439bd335d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;gwt-comshop-customization-sub-tab-panel&quot;)/table[@class=&quot;gwt-fabric-filtering-panel&quot;]/tbody[1]/tr[2]/td[1]/div[@class=&quot;gwt-comshop-fabric-swatch-scroll-panel&quot;]/div[1]/table[1]/tbody[1]/tr[3]/td[1]/table[@class=&quot;gwt-comshop-fabric-flex-table&quot;]/tbody[1]/tr[2]/td[2]/table[@class=&quot;gwt-comshop-fabric-image-panel&quot;]/tbody[1]/tr[1]/td[1]/div[@class=&quot;gwt-PDP-Fabric-Image-panel&quot;]/img[@class=&quot;gwt-pdp-swatch-thumbnail-image&quot;]</value>
      <webElementGuid>d83ec6b3-3d7b-4bc9-82ea-5c38f5426a98</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='gwt-comshop-customization-sub-tab-panel']/table/tbody/tr[2]/td/div/div/table/tbody/tr[3]/td/table/tbody/tr[2]/td[2]/table/tbody/tr/td/div/img</value>
      <webElementGuid>525b2101-8626-4812-bb48-90e3a21cdc7c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:img</name>
      <type>Main</type>
      <value>//img[@alt='Betty Floral Multi                                                                                                              ']</value>
      <webElementGuid>bee80bbd-2b8e-4dc8-8c09-3c1727f40a04</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//td[2]/table/tbody/tr/td/div/img</value>
      <webElementGuid>5e7c4286-e424-48e1-8d6f-90275efd83f5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//img[@alt = 'Betty Floral Multi                                                                                                              ' and @title = 'Betty Floral Multi                                                                                                              ' and @src = 'https://akamai-scene7.ballarddesigns.com/is/image/ballarddesigns//BFM?$wcom$']</value>
      <webElementGuid>823c569e-844d-4e6a-8a73-6e16891e4393</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
