<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>img_For fabric names and description hold m_191161_1</name>
   <tag></tag>
   <elementGuidId>d84067c6-e680-44ee-8291-1c7890980dae</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='gwt-comshop-customization-sub-tab-panel']/table/tbody/tr[2]/td/div/div/table/tbody/tr[3]/td/table/tbody/tr[4]/td[4]/table/tbody/tr/td/div/img</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>tr:nth-of-type(4) > td:nth-of-type(4) > table.gwt-comshop-fabric-image-panel > tbody > tr > td > div.gwt-PDP-Fabric-Image-panel > img.gwt-pdp-swatch-thumbnail-image</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:role=img[name=&quot;Tillie Gingham Cornflower Insideout Performance&quot;i]</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>img</value>
      <webElementGuid>325ed223-f8f6-4044-80b6-a2b9b7157251</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>gwt-pdp-swatch-thumbnail-image</value>
      <webElementGuid>b0a99d9f-9446-4d9d-9e54-608629913a10</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>alt</name>
      <type>Main</type>
      <value>Tillie Gingham Cornflower Insideout Performance                                                                                 </value>
      <webElementGuid>4c382ca6-fb61-4525-8ebb-cb2aea111ce2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-siid</name>
      <type>Main</type>
      <value>23</value>
      <webElementGuid>bd1f717c-809b-4959-9ac4-56c11c69f24b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tabindex</name>
      <type>Main</type>
      <value>0</value>
      <webElementGuid>23ba55c8-fe50-4ade-b010-895dc5187054</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>title</name>
      <type>Main</type>
      <value>Tillie Gingham Cornflower Insideout Performance                                                                                 </value>
      <webElementGuid>202c0705-f6aa-4eaf-842a-bd1718e19496</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>src</name>
      <type>Main</type>
      <value>https://akamai-scene7.ballarddesigns.com/is/image/ballarddesigns//TGCF?$wcom$</value>
      <webElementGuid>951cc464-20b1-4c8b-bb2b-064999ddb3f5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;gwt-comshop-customization-sub-tab-panel&quot;)/table[@class=&quot;gwt-fabric-filtering-panel&quot;]/tbody[1]/tr[2]/td[1]/div[@class=&quot;gwt-comshop-fabric-swatch-scroll-panel&quot;]/div[1]/table[1]/tbody[1]/tr[3]/td[1]/table[@class=&quot;gwt-comshop-fabric-flex-table&quot;]/tbody[1]/tr[4]/td[4]/table[@class=&quot;gwt-comshop-fabric-image-panel&quot;]/tbody[1]/tr[1]/td[1]/div[@class=&quot;gwt-PDP-Fabric-Image-panel&quot;]/img[@class=&quot;gwt-pdp-swatch-thumbnail-image&quot;]</value>
      <webElementGuid>24a2d891-6f48-40cb-b0f5-a7632886e2d9</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='gwt-comshop-customization-sub-tab-panel']/table/tbody/tr[2]/td/div/div/table/tbody/tr[3]/td/table/tbody/tr[4]/td[4]/table/tbody/tr/td/div/img</value>
      <webElementGuid>4274c23c-50cf-41d1-a111-71a64821a3c1</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:img</name>
      <type>Main</type>
      <value>//img[@alt='Tillie Gingham Cornflower Insideout Performance                                                                                 ']</value>
      <webElementGuid>ae23ed0b-d89e-4940-af35-54d3ca234538</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//tr[4]/td[4]/table/tbody/tr/td/div/img</value>
      <webElementGuid>12bd171d-dff1-4901-98b9-51336beb3ea1</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//img[@alt = 'Tillie Gingham Cornflower Insideout Performance                                                                                 ' and @title = 'Tillie Gingham Cornflower Insideout Performance                                                                                 ' and @src = 'https://akamai-scene7.ballarddesigns.com/is/image/ballarddesigns//TGCF?$wcom$']</value>
      <webElementGuid>22df3c62-e445-4efb-92d5-5097f9f88ec7</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
