<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>img_Latte_gwt-pdp-swatch-thumbnail-image gw_9f18c7</name>
   <tag></tag>
   <elementGuidId>4667ee11-2b0a-4519-bfaf-7b1af71a0303</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='gwt-comshop-customization-sub-tab-panel']/table[2]/tbody/tr[2]/td/div/div/table/tbody/tr[2]/td[3]/div/div/img</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>td:nth-of-type(3) > div.gwt-comshop-body-option-image-panel > div.gwt-comshop-body-option-swatch-container > img.gwt-pdp-swatch-thumbnail-image.gwt-comshop-body-option-swatch</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:role=cell[name=&quot;Walnut Walnut&quot;s] >> internal:attr=[alt=&quot;Walnut&quot;i]</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>img</value>
      <webElementGuid>5536e9c5-16fe-4fe3-a096-9dbb9b701e80</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>gwt-pdp-swatch-thumbnail-image gwt-comshop-body-option-swatch</value>
      <webElementGuid>8e1bc32f-2e0e-4f16-b373-7c015d88ee20</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>alt</name>
      <type>Main</type>
      <value>Walnut</value>
      <webElementGuid>185427b6-6c9f-4944-a627-d15a90db1043</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-siid</name>
      <type>Main</type>
      <value>28</value>
      <webElementGuid>e6359b4e-d82b-4391-80fa-d285df64dda3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tabindex</name>
      <type>Main</type>
      <value>0</value>
      <webElementGuid>81200128-a2c3-4387-aa7d-9a087ef42ee5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>src</name>
      <type>Main</type>
      <value>https://akamai-scene7.ballarddesigns.com/is/image/ballarddesigns//MCOM007WAL?$wcom$</value>
      <webElementGuid>c3bf7d40-7e5d-42d8-b123-98852b975ca7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;gwt-comshop-customization-sub-tab-panel&quot;)/table[2]/tbody[1]/tr[2]/td[1]/div[@class=&quot;gwt-com-shop-option-panel gwt-com-shop-first-option-panel&quot;]/div[1]/table[1]/tbody[1]/tr[2]/td[3]/div[@class=&quot;gwt-comshop-body-option-image-panel&quot;]/div[@class=&quot;gwt-comshop-body-option-swatch-container&quot;]/img[@class=&quot;gwt-pdp-swatch-thumbnail-image gwt-comshop-body-option-swatch&quot;]</value>
      <webElementGuid>79ffd67f-f629-42c0-88c0-de33654fd741</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='gwt-comshop-customization-sub-tab-panel']/table[2]/tbody/tr[2]/td/div/div/table/tbody/tr[2]/td[3]/div/div/img</value>
      <webElementGuid>97519482-eb6f-4258-9b86-010b43b49fdc</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:img</name>
      <type>Main</type>
      <value>//img[@alt='Walnut']</value>
      <webElementGuid>3202d05f-d849-4e3a-b386-067f00da525b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//td[3]/div/div/img</value>
      <webElementGuid>079b6f0c-3400-4afd-857b-16a094c0740d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//img[@alt = 'Walnut' and @src = 'https://akamai-scene7.ballarddesigns.com/is/image/ballarddesigns//MCOM007WAL?$wcom$']</value>
      <webElementGuid>daac1ca1-6d49-411d-8875-560d1a8317df</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
