<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>iframe_Your offer_fcopt-offer-68948-content</name>
   <tag></tag>
   <elementGuidId>afa6591a-8d73-45a4-8d5f-16e19a1028f5</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#fcopt-offer-68948-content</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//iframe[@id='fcopt-offer-68948-content']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>iframe[title=&quot;Welcome Dialog&quot;]</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>iframe</value>
      <webElementGuid>8b1fe7f2-6079-4950-a70e-5099ddee519b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>fcopt-offer-68948-content</value>
      <webElementGuid>9a678ca1-d947-483f-8bf8-989e733cf41b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>frameborder</name>
      <type>Main</type>
      <value>0</value>
      <webElementGuid>d9e27b54-fb46-42de-b6d5-05fe1aabf5a0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>width</name>
      <type>Main</type>
      <value>100%</value>
      <webElementGuid>951fa990-14c1-4bcd-9deb-8a81f8bbf842</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>height</name>
      <type>Main</type>
      <value>100%</value>
      <webElementGuid>4837999c-6437-4ed7-888f-7d2514975621</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>scrolling</name>
      <type>Main</type>
      <value>no</value>
      <webElementGuid>413e959e-5558-4fb4-a3b1-aad0acabb3d6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>title</name>
      <type>Main</type>
      <value>Welcome Dialog</value>
      <webElementGuid>66c4e798-1dff-47f3-b770-66148c833a3a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>src</name>
      <type>Main</type>
      <value>https://api.securedvisit.com/lightbox/client/1150_03659/?fp=4d5f23842f472bac6dd292399312e2a0&amp;m=form&amp;form_id=68948&amp;promo_id=8804&amp;v=1713028485692</value>
      <webElementGuid>1448f566-eabe-49c1-bcf5-453a3b8eeff3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;fcopt-offer-68948-content&quot;)</value>
      <webElementGuid>2c3c008f-4232-41b3-96cd-00d9f9258e90</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//iframe[@id='fcopt-offer-68948-content']</value>
      <webElementGuid>3b2a9666-de6b-41c8-b342-ba0762186a30</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='fcopt-onsite-app-68948_wrapper']/div[2]/div/div/iframe</value>
      <webElementGuid>0ca4bae3-a407-466e-8729-174cd3483690</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div/div/iframe</value>
      <webElementGuid>a80cb72c-a131-4804-87e2-050a19d90876</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//iframe[@id = 'fcopt-offer-68948-content' and @title = 'Welcome Dialog' and @src = 'https://api.securedvisit.com/lightbox/client/1150_03659/?fp=4d5f23842f472bac6dd292399312e2a0&amp;m=form&amp;form_id=68948&amp;promo_id=8804&amp;v=1713028485692']</value>
      <webElementGuid>93c4a713-4d7c-4c1c-81c4-9ec62c39f2fd</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
