<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>span_X</name>
   <tag></tag>
   <elementGuidId>a346d907-d61b-40c9-bab4-28c4bf9ec4ab</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#Close1-Item124 > button.offer-control.close > span</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='Close1-Item124']/button/span</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:label=&quot;Close Dialog&quot;s</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>span</value>
      <webElementGuid>e1876e46-0a9f-4410-9b97-4a8362f86df3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>X</value>
      <webElementGuid>2868c908-72d3-4521-bb33-6f9200683e97</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;Close1-Item124&quot;)/button[@class=&quot;offer-control close&quot;]/span[1]</value>
      <webElementGuid>062ccb3e-a757-46eb-8572-6f12e0d162e6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ref_element</name>
      <type>Main</type>
      <value>Object Repository/Page_Ballard Personalized Christmas Stockin_e18856/iframe_Your offer_fcopt-offer-68948-content</value>
      <webElementGuid>9e88c7fa-e6d7-4278-8cf3-fca2871d2300</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='Close1-Item124']/button/span</value>
      <webElementGuid>34530b5f-4421-4bd7-ae14-f4708fcb7e3d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='NO THANK YOU'])[1]/following::span[1]</value>
      <webElementGuid>3b2a4721-e991-4576-a38a-1382b26b9b64</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='By clicking submit, you agree to receive emails from Ballard Designs.'])[1]/following::span[2]</value>
      <webElementGuid>4d95494d-28d7-45c1-8156-2f31f97823cc</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='X']/parent::*</value>
      <webElementGuid>a38df2ef-db5d-470d-8c0d-11f2d01c238a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[9]/button/span</value>
      <webElementGuid>ffa986ea-116a-40ed-9a8a-17bcfd552c3d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//span[(text() = 'X' or . = 'X')]</value>
      <webElementGuid>c679d6fb-f351-47b8-bad5-c1d2e6214e0b</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
